### ISSUE TITLE
[Feature request] arm64 image on dockerhub

### ISSUE THREAD

**Issue by zhabba** [stilliard/docker-pure-ftpd#100]
It would be great if you provide also arm64 image on hub.docker.com
Is it possible?
Thank you.

**Comment by stilliard** [comment]
Hey @zhabba 
Thanks for the feature request!

I don't have a arm64 machine to build on atm but if you do you could build the latest version and publish it with the name pure-ftpd-arm64 :)

It it works well I could link to it from this repo for anyone else looking for arm64 support too.

**Comment by zhabba** [comment]
Hi, @stilliard 
Please find arm64 build at https://hub.docker.com/r/zhabba/pure-ftpd-arm64
Build it as is, without any modifications.

**Comment by stilliard** [comment]
Thanks @zhabba it looks awesome!
I've added a link to this from the readme file https://github.com/stilliard/docker-pure-ftpd/commit/562c7fb3b716ab8f77e62cb3177b98935e1b68e3
