### ISSUE TITLE
pure-ftpd exited with code 252  when activating --tls=*

### ISSUE THREAD

**Issue by c-pid** [stilliard/docker-pure-ftpd#103]
Hello!

When running the container via docker-compose and having TLS enabled, pure-ftpd crashed with error code 252 pretty much as in issue #64.

docker-compose:
 
```
version: "3"

services:
    ftp-red:
        image: stilliard/pure-ftpd:hardened
        container_name: ftp-red
        privileged: true
        ports:
            - "21:21"
            - "30000-30009:30000-30009"
        volumes: # remember to replace /folder_on_disk/ with the path to where you want to store the files on the host machine
            - "reddrop:/home/file_service/"
            - "/tmp/test/passwd:/etc/pure-ftpd/passwd"
            #- "/tmp/test/ssl:/etc/ssl/private/"
# uncomment for ssl/tls, see https://github.com/stilliard/docker-pure-ftpd#tls
        environment:
            PUBLICHOST: "localhost"
            FTP_USER_NAME: file_service
            FTP_USER_PASS: file_service_password
            FTP_USER_HOME: /home/file_service
            ADDED_FLAGS: "--tls=2"
            TLS_CN: "DE"
            TLS_ORG: "TestOrg"
            TLS_C: "TEST"
            
        restart: always
        
volumes:
    reddrop:  
```

Log:

> ftp-red    | Generating self-signed certificate
> ftp-red    | Generating DH parameters, 2048 bit long safe prime, generator 2
> ftp-red    | This is going to take a long time
> ftp-red    | ...................................................................................................................................................................................................................................................+............................................................................................................................................................................................................................+.......................................................................+.......................................+............................................+....................................................................................................................................................................................................................................................+.............................................................................................................................+...............+................................................+...................................................................................+....................................................................................................................+..............+...............................................................................................+..................+.....+.....................................................................................................................................+............................................................+.........................................................................................................................................+.............................................................................................................................+...............................+......................+...........................................................................................................................................+.......................................+...............+....................+......................................................................................................+................................................................................................+...........................................................................................................................................................................................+.............................................+.........................................................................................+...................+.........................................................+...........................+..............+............+....................+................................................................................................................................+......+............................+.......+....................................................................................................................+.........................................................................+.......................................................................................+..................+...............................................+..................................................+.............................................+.....................................................................................................................................................................................................................................................................................................................................+..............+..................................+......................................................................................................................................................................................................................+.................................................................+.......................................................................................................................................................................................................................................................+.......................+..................................................................................................................................................................................................+.................................................................................................................................................+....................................................................................................+......+...................................................................................................................................................................................................................................................................+.....................................................................+.............................................................................................................................................................+........................................................................................................................................................................................+.................................+.............................................................................................................................................................................................................+......................................+.....................+.............................................................+..........................+...................................................+............................................................................................................................................................+........................+.........................................................................+.............................................+.............................................+...................................................+......................................+...............................................................................................................+......................................................................................................................................+......................+.....................................................................................+......................+.................................................................................................................+...........................................................................................+...............................................................+......................................+.......................................................................................................................................................................+......................................................+.....+................................................+.............................................................+......+...............................................................................................................................................................................................................................................................................................................................+.......................................................+.......+.............................................+.......................................+..................................+...........................+...............................................+........................+.........................................+........................................+...........++*++*++*++*
> ftp-red    | Generating a RSA private key
> ftp-red    | ..............+++++
> ftp-red    | ..........+++++
> ftp-red    | writing new private key to '/etc/ssl/private/pure-ftpd.pem'
> ftp-red    | -----
> ftp-red    | problems making Certificate Request
> ftp-red    | 139884506320960:error:0D07A097:asn1 encoding routines:ASN1_mbstring_ncopy:string too long:../crypto/asn1/a_mbstr.c:109:maxsize=2
> ftp-red    | Creating user...
> ftp-red    | Password:
> ftp-red    | Enter it again: Error.
> ftp-red    | Check that [file_service] doesn't already exist,
> ftp-red    | and that [/etc/pure-ftpd/passwd/pureftpd.passwd.tmp] can be written.
> ftp-red    |
> ftp-red    | Setting default port range to: 30000:30009
> ftp-red    | Setting default max clients to: 5
> ftp-red    | Setting default max connections per ip to: 5
> ftp-red    | Starting Pure-FTPd:
> ftp-red    |   pure-ftpd  -l puredb:/etc/pure-ftpd/pureftpd.pdb -E -j -R -P localhost -s -A -j -Z -H -4 -E -R -G -X -x --tls=2  -p 30000:30009 -c 5 -C 5
> ftp-red exited with code 252

**Comment by stilliard** [comment]
Hi @c-pid 

Could you please try changing your tls params to the following:

```
            TLS_CN: "localhost"
            TLS_ORG: "TestOrg"
            TLS_C: "DE"
            TLS_USE_DSAPRAM=true
```

Noticed you had the CN & C parts switched, also using CN as localhost but feel free to change to your hostname. 

Also added TLS_USE_DSAPRAM to test with to see if that helps. 
Let me know how it goes.

**Comment by c-pid** [comment]
I feel like an idiot. Yes, that fixed it. Thank you very much. TLS_USE_DSAPRAM had no effect, it was the switched Country Code and Common Name...

**Comment by stilliard** [comment]
Hey @c-pid 
No worries, I probably need to add better docs for the TLS options available. 
Glad it's all working for you now :+1:
