### ISSUE TITLE
Can You add option to allow anonymous users?

### ISSUE THREAD

**Issue by zuber1979** [stilliard/docker-pure-ftpd#104]
Can You add a configuration parameter do enable/disable -E option (enable anonymous access) ?

**Comment by stilliard** [comment]
Hi @zuber1979 , thanks for the feature idea, it might be one for the future but atm i'm trying to avoid adding too many new options where flags exist for pure-ftpd. 

Currently the best way of doing this is to change the run command, either by specifying it when calling `docker run` or extend the project to set a different `RUN` command in the Dockerfile.
There's a couple examples of this at the top of the readme here:
https://github.com/stilliard/docker-pure-ftpd#docker-pure-ftpd-server

Hope this helps.

**Comment by zuber1979** [comment]
Yes, I know that I can modify Dockerfile by myself.

I just thought I would be good to just have such configuration possibility out of the box.

**Comment by stilliard** [comment]
Oh, sorry I didn't mean you had to edit the Dockerfile itself, but instead you could create a simple one off the back to simplify the run usage.

Alternatively, without any Dockerfile changes, you can set the run command when calling `docker run` effectively giving you access to all the same [flags as pure-ftpd](https://linux.die.net/man/8/pure-ftpd) has.
Here's the example from the readme:

```
docker run --rm -d --name ftpd_server -p 21:21 -p 30000-30009:30000-30009 stilliard/pure-ftpd:hardened bash /run.sh -c 30 -C 10 -l puredb:/etc/pure-ftpd/pureftpd.pdb -E -j -R -P localhost -p 30000:30059
```

Closing for now as no plans atm to add additional options but I hope the above helps :+1:
Thanks

**Comment by zuber1979** [comment]
Right, thanks for help, I modified docker-compose file:

entrypoint: /run.sh -c 30 -C 10 -l puredb:/etc/pure-ftpd/pureftpd.pdb -j -R -P localhost -p 30000:30059
