### ISSUE TITLE
How can I login FTP by root account

### ISSUE THREAD

**Issue by DTbelieveIT** [stilliard/docker-pure-ftpd#105]
Hi,I hope to login FTP by ```root account```.Because I want to upload some file to every folder without the limit of permissions.I know this way is ```insecure``` but also I wonder how to do it.
Thanks for your help: )

**Comment by stilliard** [comment]
Hi @DTbelieveIT ,
I believe you could do this with the -u0 flag but i've never tried sorry, you can pass this and any other flags you need to the container when running it by running the /usr/sbin/pure-ftpd directly. 
Might be a question for stackoverflow, hope this helps.

**Comment by DTbelieveIT** [comment]
@stilliard : ) Thank you for you reply!  I have try a lot of ways but it dosen't work. 
1. I comment the following in  /etc/pure-ftpd/conf/MinUID
```
# 1000 
```
2. I comment root in /etc/ftpusers
```
# /etc/ftpusers: list of users disallowed FTP access.
# root
daemon
bin
....
```
3. I also add "-u 0 -g 0" flag in /run.sh
```bash
....
# Set max connections per ip in pure-ftpd options if not already existent
if [[ $PURE_FTPD_FLAGS != *" -C "* ]]
then
    echo "Setting default max connections per ip to: $FTP_MAX_CONNECTIONS"
    PURE_FTPD_FLAGS="$PURE_FTPD_FLAGS -C $FTP_MAX_CONNECTIONS"
fi

PURE_FTPD_FLAGS="-u 0 -g 0 $PURE_FTPD_FLAGS"
# let users know what flags we've ended with (useful for debug)
echo "Starting Pure-FTPd:"
echo "  pure-ftpd $PURE_FTPD_FLAGS"

# start pureftpd with requested flags
exec /usr/sbin/pure-ftpd $PURE_FTPD_FLAGS
```

Finish all above actions, I exec ```/etc/init.d/pure-ftpd restart``` in container and  exec ```docker-compose restart``` out of the container. 

haha... but it failed, I am a little unwilling 囧

**Comment by stilliard** [comment]
Hi @DTbelieveIT 
ah interesting, you could try looking at the docker logs for the container to see if the command flags it's started with look correct too in case one of the defaults we set is overriding yours.
Also, the /etc/ftpusers change, are you doing this before pure-ftpd starts up? Not sure if it applies after it's already running and might be being reverted if you edit and then restart the container. 
Hope this helps.
