### ISSUE TITLE
Active mode not work. return500 I won't open a connection to 10.21.38.117 (only to 172.17.0.1) 425 No data connection, thanks

### ISSUE THREAD

**Issue by zoukewang** [stilliard/docker-pure-ftpd#106]
500 I won't open a connection to 10.21.38.117 (only to 172.17.0.1)
425 No data connection

**Comment by stilliard** [comment]
Hi @zoukewang 
Have you tried setting the PUBLICHOST to the IP of the host/server you're connecting to?

**Comment by zoukewang** [comment]
> Hi @zoukewang
> Have you tried setting the PUBLICHOST to the IP of the host/server you're connecting to?

hi stilliard, i have set the PUBLICHOST to my host ip,  The following is my run cmd:  (on linux: passive/active mode is all OK, but on mac  active mode return: 500 I won't open a connection to 10.21.38.117 (only to 172.17.0.1),  I aslo try set mac ip_forward enable, but still useless)  thanks 

ip=10.21.38.117
docker run -d --name ftp -p 21:21 -p 30000-30029:30000-30029 -e PUBLICHOST=${ip} -e FTP_USER_NAME=nfvo -e FTP_USER_PASS=nfvo -e FTP_USER_HOME=/home/ftpusers/nfvo -e FTP_PASSIVE_PORTS=30000:30029 --expose=30000-30029 --privileged=true -v /Users/zoukewang/mywork/asiainfo/docker/ftp/data/nfvo:/home/ftpusers/nfvo stilliard/pure-ftpd:hardened

**Comment by stilliard** [comment]
Interesting, it sounds like it might be a firewall issue. 
I don't have a mac but a quick search around returned the following ideas to try:
https://fetchsoftworks.com/fetch/help/Contents/Tutorial/ConfiguringMacOSFirewall.html
https://discussions.apple.com/thread/447657
Hope this helps.

**Comment by stilliard** [comment]
Hey @zoukewang , 
Did you find what was causing this in the end?

**Comment by davidpetro88** [comment]
I have same problem when I try connect with a Java client

**Comment by jackzhangpython** [comment]
> Hi @zoukewang
> Have you tried setting the PUBLICHOST to the IP of the host/server you're connecting to?

solved this problem

**Comment by rljunggren** [comment]
@jackzhangpython   How did you solve the Issue?

**Comment by matteoopenf** [comment]
> @jackzhangpython How did you solve the Issue?

how did you solve?
