### ISSUE TITLE
Got error 500, on a mounted volume

### ISSUE THREAD

**Issue by vipera7** [stilliard/docker-pure-ftpd#109]
I want to access to n object storage with ftp and be able to do some action. Right now I can access and view files/folders from it, but I can't do action, like rename a file, create a dir...

Here is my mounted volume in my host:
`drwxrwxr-x.   1 root root     0 Jan  1  1970 mnt`

I'm using the following command to create a container : 
`docker run -d --name ftpd_server -p 21:21 -p 30000-30009:30000-30009 -e "PUBLICHOST=123.123.123.123" -v /mnt:/home/ftpusers/root stilliard/pure-ftpd:latest`

Then I enter in the container with : 
`docker exec -it ftpd_server /bin/bash`

And create the user

 `pure-pw useradd root -f /etc/pure-ftpd/passwd/pureftpd.passwd -m -u ftpuser -d /home/ftpusers/root`

(*Do I have to put root as ftp user ?*)

Then I get this when I try to create a dir

![Error](https://i.imgur.com/8LDR7P7.png)

And I can see my contents

**Comment by stilliard** [comment]
Hi @vipera7 ,
Seems like a permission issue, i've not run into this myself another user had an issue with permissions before, maybe the comments here can help: https://github.com/stilliard/docker-pure-ftpd/issues/35#issuecomment-325583705

**Comment by vipera7** [comment]
I have tried the following command `pure-pw useradd root -f /etc/pure-ftpd/passwd/pureftpd.passwd -m -u ftpuser -d /home/ftpusers/root` but sadly I have the same issue

**Comment by stilliard** [comment]
I think you could try using the uid as the -u flag instead of root and -g as the group id.
If that doesn't work it's probably best to ask on stackoverflow if you haven't already with the pureftpd tag, hopefully someone on there can help.

**Comment by vipera7** [comment]
I have to use the root uid ?

**Comment by vipera7** [comment]
I also tried to give ftpuser root privilege and change in /etc/pure-ftpd/passwd/pureftpd.passwd to change from 1000;1000 to 0.0 but the problem persist

**Comment by stilliard** [comment]
Hi @vipera7 ah that's a shame, i've not had any experience with object storage but worth asking on stackoverflow if you haven't already with the pureftpd tag, hopefully someone on there can help :+1:

**Comment by vipera7** [comment]
I got an answer that doesn't help, I will give a bounty on the question, we will see if someone can figure it out

**Comment by vipera7** [comment]
I found some new info about my issue. I'm using now this following command to create the container : 

`docker run -d --name ftpd_server -p 21:21 -p 30000-30009:30000-30009 -v /home/foo/data:/home/ftpusers/foo -e FTP_USER_UID=1000 -e FTP_USER_GID=1000 -e FTP_USER_NAME=foo -e FTP_USER_PASS=pass -e FTP_USER_HOME=/home/ftpusers/foo stilliard/pure-ftpd`

On my host machine I have created a new user named foo which have uid = 1000 and gid = 1000. 

I have the following path : 

```
home
│
└───foo
    │
    └───data
        │ File (root.root)
        │
        └───data2  (foo;foo)
            │ File2 (foo.foo)
```

I have made the following command before running the container to give permission to user foo :  

chown -R foo.foo /home/foo/data*



Now I can write into folder data2 but I can't do anything before this folder (access denied)

**Comment by finex** [comment]
I'm also having a problem renaming files: I've created a virtual user with manula uid/gid from the host machine. Create/Upload/Delete files works fine, rename doesn't. I've also tried to set the value `no` on `/etc/pure-ftpd/conf/NoRename` but without any change.

**Comment by mryauch** [comment]
@finex Are you using the hardened branch? I just ran into this and found that the Dockerfile in the hardened branch looks like this:
`# startup
CMD /run.sh -l puredb:/etc/pure-ftpd/pureftpd.pdb -E -j -R -P $PUBLICHOST -s -A -j -Z -H -4 -E -R -G -X -x`

The `-G` is for norename and is likely what is causing this. I also can't figure out a way to get additional flags to change this behavior.

**Comment by joseluisq** [comment]
@mryauch I have verified  it works. 👍

**Comment by finex** [comment]
@myrauch: you're right. I was using that branch. Later I found that flag and I've switched to the other image manually adding some security flags but I've forgot to report it here.
