### ISSUE TITLE
Invalid containerPort: 30000-30009

### ISSUE THREAD

**Issue by bluepuma77** [stilliard/docker-pure-ftpd#11]
I am running Docker version 1.3.3 on Debian 8 Jessie.

When trying to run the example from the docs I receive an error message
```
sudo docker run -d --name ftpd_server -p 21:21 -p 30000-30009:30000-30009 -e "PUBLICHOST=localhost" stilliard/pure-ftpd
Invalid containerPort: 30000-30009
```
Do I need to address the ports individually instead? That seems to work.
```-p 21:21 -p 30000:30000 -p 30001:30001 -p 30002:30002 ...```

**Comment by stilliard** [comment]
Hi @bluepuma77,
I think it's only the more recent versions of docker where you can specify port ranges sorry. 
But yes specifying the ports individually should work too.

**Comment by stilliard** [comment]
Hi @bluepuma77 , Is this resolved for you now?
