### ISSUE TITLE
[Question] Problem deploying using docker stack file

### ISSUE THREAD

**Issue by jlcarpenter** [stilliard/docker-pure-ftpd#112]
I am trying to deploy to docker instance using the following stack configuration.

> ftp:
>    image: stilliard/pure-ftpd:hardened
>    deploy:
>      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: foo
      FTP_USER_PASS: pass
      FTP_USER_HOME: /home/foo
    volumes:
      - /myfilepath:/home/foo
    ports:
      - "2111:21"
      - "2011:20"
      - "30000-30009:30000-30009"
    networks:
      - my-overlay

When I look at the logs, all I see is:

>2019-06-12T19:12:52.470081985Z Creating user...
>2019-06-12T19:12:52.482891626Z Password: 
>2019-06-12T19:12:52.507511813Z Enter it again: 

When I try to connect using Filezilla, I get "Connection attempt failed with "ECONNREFUSED - Connection refused by server"."

**Comment by stilliard** [comment]
Hi @jlcarpenter 
Your stack config looks good to me, maybe try without the custom my-overlay network and see if there's something causing an issue. Hope that helps.

**Comment by jlcarpenter** [comment]
Thanks, I was able to resolve the issue by putting quotes around the volume paths
