### ISSUE TITLE
why use a non-standard location for the passwd file?

### ISSUE THREAD

**Issue by kamaradski** [stilliard/docker-pure-ftpd#114]
in your documentation you mention to create new users like this:

`pure-pw useradd bob -f /etc/pure-ftpd/passwd/pureftpd.passwd -m -u ftpuser -d /home/ftpusers/bob`

but the default location for the `pureftpd.passwd` file would be: `/etc/pure-ftpd/pureftpd.passwd`

Is there a specific reason for not using the default location? and am I free to not use the -f flag and let pure-ftpd use it's default location without breaking anything in the current setup?

also:
How is this impacting the `pure-pw mkdb` command? as far as I know, it is not possible to speficy a non-default location from where it reads the passwd file from?

**Comment by stilliard** [comment]
Hi @kamaradski ,
Aha I hadn't even noticed we were using a non standard default in our readme. Feel free to use any location :)
Ref mkdb call, you can pass `-f` to set this path too :) Hope this helps.
