### ISSUE TITLE
docker-pure-ftpd on Raspberry Pi 3 (Photon OS)..failing

### ISSUE THREAD

**Issue by stoltzmr** [stilliard/docker-pure-ftpd#115]
Hi there, got error log after docker run:

{"log":"standard_init_linux.go:190: exec user process caused \"exec format error\"\n","stream":"stderr","time":"2019-06-14T09:59:19.540272466Z"}

Seems to not run on the arm processor....any advice?

**Comment by stilliard** [comment]
Hi @stoltzmr , there's a separate arm build available here: https://hub.docker.com/r/zhabba/pure-ftpd-arm64
Hope this helps.

**Comment by stoltzmr** [comment]
Thanks very much Andrew!

Markus

**Comment by tkhosravi** [comment]
Hi,
I hit the same error, not matter if I use the original stilliard/pure-ftpd image or the zhabba/pure-ftpd-arm64 one.
@stoltzmr did it work for you ?
Thanks

**Comment by stoltzmr** [comment]
Hi, nope it did not.

Regards
Markus

**Comment by tkhosravi** [comment]
Hi,
FYI, I finally found an image that works, it's crazymax/pure-ftpd :)
Hope it helps

**Comment by stoltzmr** [comment]
Much appreciated!

Mind regards
Markus
