### ISSUE TITLE
capabilities in container

### ISSUE THREAD

**Issue by goochjj** [stilliard/docker-pure-ftpd#116]
Seems like stock pure-ftpd wants more capabilities than docker supplies, specifically those supplied in caps_p.h
```
# if defined(USE_PAM) && defined(CAP_AUDIT_WRITE)
    CAP_AUDIT_WRITE,
# endif
    CAP_SETGID,
    CAP_SETUID,
    CAP_CHOWN,
    CAP_NET_BIND_SERVICE,
    CAP_SYS_CHROOT,
    CAP_SYS_NICE,
    CAP_DAC_READ_SEARCH
```

Docker in particular does not supply CAP_SYS_NICE, or CAP_DAC_READ_SEARCH.

The solution in the Dockerfile is to disable capabilities entirely, but it's nice for security that pure-ftpd can limit itself further than the capability set provided.  The better solution is to just remove the two capabilities that prevent the daemon from loading.  Better yet, if upstream would check to see if the capabilities it wants to "keep" are already assigned or not first, then the error would go away.

Quick fix is to remove those from the .h file and then it'll start and work.

Daemon Without Capabilities:
Capabilities for `92': = cap_chown,cap_dac_override,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_net_bind_service,cap_net_raw,cap_sys_chroot,cap_mknod,cap_audit_write,cap_setfcap+eip

Daemon with Capabilities and 2 removed:
Capabilities for `62': = cap_chown,cap_setgid,cap_setuid,cap_net_bind_service,cap_sys_chroot,cap_audit_write+ep

User process without capabilities:
Capabilities for `98': = cap_chown,cap_dac_override,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_net_bind_service,cap_net_raw,cap_sys_chroot,cap_mknod,cap_audit_write,cap_setfcap+i

User process with capabilities:
Capabilities for `125': =

PR forthcoming...

**Comment by stilliard** [comment]
Closed ref #117
