### ISSUE TITLE
Pure-FTPD on Kubernetes

### ISSUE THREAD

**Issue by thzois** [stilliard/docker-pure-ftpd#119]
Hello,

This is not an issue but instead I would like a piece of advice if you are familiar with the topic. I am running the image on Kubernetes and I am using as `PUBLICHOST` the externalIP of the node. But it seems when I try to connect something is failing and I cannot get the directory. This is the error below: 

```
Command: MLSD
Error: The data connection could not be established: ECONNREFUSED - Connection refused by server
```

Any idea on what it might fails? Thank you very much!

**Comment by stilliard** [comment]
Hi @thzois 
Interesting, i've not used Kubernetes sorry so i'm not sure how much help I'll be, it may be worth asking this question over on stackoverflow.

If it helps, my checks would be that all the needed ports are opened on the host firewall & through Kubernetes for the container. It'd need 21, as well as ports 30000 through to 30009 (by default though you can change this).

Hope this helps.

**Comment by thzois** [comment]
Hello @stilliard,
It is probably because of the port-range. Kubernetes does not support that one yet.. I will just deploy it as a docker container. 

Thank you for your quick response.
