### ISSUE TITLE
pure-ftpd exited with code 252

### ISSUE THREAD

**Issue by Amine27** [stilliard/docker-pure-ftpd#122]
Hello,
When I activate TLS, the container stop without much informations :

> pure-ftpd      | Creating user... 
> pure-ftpd      | Password:  
> pure-ftpd      | Enter it again: Error. 
> pure-ftpd      | Check that [wallesmart] doesn't already exist, 
> pure-ftpd      | and that [/etc/pure-ftpd/passwd/pureftpd.passwd.tmp] can be written. 
> pure-ftpd      |  
> pure-ftpd      | Setting default port range to: 30000:30009 
> pure-ftpd      | Setting default max clients to: 5 
> pure-ftpd      | Setting default max connections per ip to: 5 
> pure-ftpd      | Starting Pure-FTPd: 
> pure-ftpd      |   pure-ftpd  -l puredb:/etc/pure-ftpd/pureftpd.pdb -E -j -R -P www.user.com -s -A -j -Z -H -4 -E -R -G -X -x --tls=2  -p 30000:30009 -c 5 -C 5 
> pure-ftpd exited with code 252
> 

When I start pure-ftpd without docker (installed on system), using the same command and the same certificates, it just works.

`pure-ftpd  -l puredb:/etc/pure-ftpd/pureftpd.pdb -E -j -R -P www.user.com -s -A -j -Z -H -4 -E -R -G -X -x --tls=2  -p 30000:30009 -c 5 -C 5 `

My docker-compose.yml :

> version: '2'
> services:
>   ftpd_server:
>     image: stilliard/pure-ftpd:hardened
>     container_name: pure-ftpd
>     ports:
>       - "21:21"
>       - "30000-30009:30000-30009"                                                                                                                                                               
>     volumes:
>       - "./data:/home/user/"
>       - "./passwd:/etc/pure-ftpd/passwd"                                                                                            
>       - "./ssl:/etc/ssl/private/"                                                                                                                                                              
>     environment:
>       PUBLICHOST: "www.user.com"
>       FTP_USER_NAME: user
>       FTP_USER_PASS: pass
>       FTP_USER_HOME: /home/user
>       ADDED_FLAGS: "--tls=2"                                                                                                                                                           
>     restart: always

Any help ?
Thank you.

**Comment by stilliard** [comment]
Hi @Amine27 ,
Apologies for the very delayed reply. 

Not sure if you've already solved this but it might be worth double checking inside the container that the /etc/ssl/private/pure-ftpd.pem file pulls through correctly and the permissions on the file are 600.

Or alternatively a similar issue was reported and resolved here: maybe the comments in this issue might help: https://github.com/stilliard/docker-pure-ftpd/issues/103

**Comment by dszymczuk** [comment]
Hi,

I would like to implement using certs with let's encrypt . I'm using https://github.com/jwilder/nginx-proxy for achieving certs.
I have external volume to store certs. Here is result:

```shell
root@f365d0cb307e:/certs/DOMAIN# ls -la
total 32
drwxr-xr-x 2 root root 4096 Mar 19 13:08 .
drwxr-xr-x 9 root root 4096 Mar 18 19:06 ..
-rw-r--r-- 1 root root    0 Mar 19 13:08 .companion
lrwxrwxrwx 1 root root   67 Mar 19 13:08 account_key.json -> ../accounts/acme-v02.api.letsencrypt.org/directory/default_key.json
lrwxrwxrwx 1 root root   67 Mar 19 13:08 account_reg.json -> ../accounts/acme-v02.api.letsencrypt.org/directory/default_reg.json
-rw-r--r-- 1 root root 2255 Mar 18 11:15 cert.pem
-rw-r--r-- 1 root root 1646 Mar 18 11:15 chain.pem
-rw-r--r-- 1 root root 3902 Mar 18 11:15 fullchain.pem
-rw-r--r-- 1 root root 3271 Mar 18 11:15 key.pem
```

Anyway, I created fork and updated run.sh to copy certs to /etc/ssl/private/pure-ftpd.pem .
So I found this gist:
https://gist.github.com/nosmall/37c240a4e4e8e1280ecf966d5cca4bf3
and use some code:

```shell
echo "Cert Enabled"
rm /etc/ssl/private/pure-ftpd.pem
cat /$VOLUME_NAME/$CERT_HOST/cert.pem /$VOLUME_NAME/$CERT_HOST/key.pem > /etc/ssl/private/pure-ftpd.pem
chmod 600 /etc/ssl/private/*.pem
ls -la /etc/ssl/private/
```

Result this code is:
```shell
Cert Enabled
rm: cannot remove '/etc/ssl/private/pure-ftpd.pem': No such file or directory

total 16
drwx------ 1 root root 4096 Mar 19 13:03 .
drwxr-xr-x 1 root root 4096 Jan 22 14:35 ..
-rw------- 1 root root 5526 Mar 19 13:03 pure-ftpd.pem

Creating user...
Password:
Error.
Check that [USERNAME] doesn't already exist,
and that [/etc/pure-ftpd/passwd/pureftpd.passwd.tmp] can be written.
Enter it again:
Setting default port range to: 30000:30009
Setting default max clients to: 5
Setting default max connections per ip to: 5
Starting Pure-FTPd:
  pure-ftpd  -l puredb:/etc/pure-ftpd/pureftpd.pdb -E -j -R -P DOMAIN --tls=2  -p 30000:30009 -c 5 -C 5
```


And the container is restarting every time.
You can see that cert exists and has correct permission ( 600 ).
I tested copy just 
`/$VOLUME_NAME/$CERT_HOST/cert.pem > /etc/ssl/private/pure-ftpd.pem`
Also container is restarting everytime.

**Without certs everything is ok.**

What did I do wrong?

**Comment by stilliard** [comment]
@dszymczuk apologies I didn't spot your reply here before. 
I've not tried that before, did you ever get this working?

**Comment by kolserdav** [comment]
I had this issue when I passed:
```yml
- FTP_PASSIVE_PORTS="35001:35010"
```
And then I change it to:
```yml
- FTP_PASSIVE_PORTS=35001:35010 # Delete double quotas
```
so it works.
