### ISSUE TITLE
Exec script on success upload

### ISSUE THREAD

**Issue by Classsic** [stilliard/docker-pure-ftpd#123]
Hi, is this module compiled with pure-uploadscript  option?
I follow this question [,](https://stackoverflow.com/questions/7644533/proftpd-verify-complete-upload/12339611) but not sure how implement in this docker image.
Thanks in advanced.

**Comment by Classsic** [comment]
I can´t login when try the flag -o, like this: `-e ADDED_FLAGS=-o` 
Without the flags, all work perfect.
Any clue?
Thanks

**Comment by stilliard** [comment]
Hi @Classsic ,
We don't currently compile with the `--with-uploadscript` flag but you could try editing the `Dockerfile` where we run `./configure` here I believe to try adding this in: https://github.com/stilliard/docker-pure-ftpd/blob/master/Dockerfile#L26

If it works please let me know and we could merge it here into the main project, thanks
