### ISSUE TITLE
Plan of realeases

### ISSUE THREAD

**Issue by Lukier1** [stilliard/docker-pure-ftpd#125]
Hello,
I have noticed that the last release/stable tags were done 5 years ago. Do you have a plan for create more current tags?

Thanks!

**Comment by stilliard** [comment]
Hi @Lukier1,
Thanks for contacting!

The tags here on github show out of date sorry as i've only been updating them on docker hub. *I'll probably remove the tags all together here so they are all in once place.*

There's a new latest tag on there from last month, hope that helps:

https://hub.docker.com/r/stilliard/pure-ftpd/tags

:)
