### ISSUE TITLE
How can I change server port 21 to other port(e.g. 11121)

### ISSUE THREAD

**Issue by jujis008** [stilliard/docker-pure-ftpd#127]
I running docker-compose with the configuration file:
`services:

  ftp:
    image: stilliard/pure-ftpd:hardened
    environment:
      - FTP_USER_NAME=test
      - FTP_USER_PASS=abcd
      - FTP_USER_HOME=/home/test
    volumes:
      - test-data:/home/test
    ports:
      - "12321:21"
      - "30000-30009:30000-30009"
    network_mode: host
    restart: unless-stopped`

when I run up server still running at port 21.
How can I change to my specific port?

**Comment by stilliard** [comment]
Hey @jujis008 

I've tested your example file and it looks like the `network_mode: host` line causes it to not work, commenting this out or removing it fixes the issue for me. 

I've found the following link which seems to suggest the port mapping doesn't work with network_mode: host
https://docs.docker.com/compose/compose-file/#ports

Hope this helps.

**Comment by jujis008** [comment]
Exactly as you said, I changed network_mode type to default(bridge) but got another problem, 
`230 OK. Current directory is /
Remote system type is UNIX.
Using binary mode to transfer files.
ftp> ls
500 I won't open a connection to 127.0.0.1 (only to 172.17.0.1)
ftp: bind: Address already in use
ftp> `

**Comment by stilliard** [comment]
Ah no worries, this error happens when pure-ftpd can't bind the address, try adding the following to the environment section: `PUBLICHOST: "localhost"`

**Comment by jujis008** [comment]
Yes, I did, but the same thing happened.BTW, I'm using ubuntu OS.

**Comment by stilliard** [comment]
That's cool, I'm on ubhntu too. 
Could you paste me your latest compose file please? Thank you

**Comment by jujis008** [comment]
Thank you stilliard~, here is the compose file
`version: '3'

services:
  ftp:
    image: stilliard/pure-ftpd:hardened
    environment:
      - FTP_USER_NAME=user
      - FTP_USER_PASS=pass
      - FTP_USER_HOME=/home/user
      - PUBLICHOST=localhost
    volumes:
      - user-data:/home/user
    ports:
      - "11121:21"
      - 30000-30009:30000-30009
    network_mode: default
    restart: unless-stopped

volumes:
  user-data:
    driver: local
`

**Comment by stilliard** [comment]
Hi @jujis008 
Hope you're doing well and staying safe.

Sorry I missed your reply here. 
Start of the year became pretty busy unfortunately. 

Not sure if you resolved this issue yourself in the end but looking through I've not seen `network_mode: default` before, maybe try removing that line and see if that fixes it. 

Otherwise, my other suggestion is to try the compose example in the repo: https://github.com/stilliard/docker-pure-ftpd/blob/master/docker-compose.yml
It's a v2 example rather than v3 like yours but still works with the latest docker-compose.
