### ISSUE TITLE
Question: How to connect for the ftp server from external application?

### ISSUE THREAD

**Issue by Assafkalfa** [stilliard/docker-pure-ftpd#129]
Hello and I'm sorry if my question is a little stupid. I'm not a DevOps and never created a server. But need to check some things and have no time to wait for our DevOps to establsh new server...

I run the image and success to enter the server :)
Need a help with how to connect to the server, for example with FileZila.

I try this:
`docker run -d --name ftpd_server -p 21:21 -p 30000-30009:30000-30009 -e "PUBLICHOST=localhost" stilliard/pure-ftpd`

But didn't success to make connection (host: localhost; port: 21; username and password empty, pure_ftpd, stillard, ftpd_server...)

Will be glad for help (also to add a password for the connection will be nice too)
Sorry for the simple question..

Thank you!

P.S. Env: Windows

**Comment by stilliard** [comment]
Hi @Assafkalfa 
Happy to help out. 

After running the container you need to exec into the container and setup the user/password, here's a guide for this:
https://github.com/stilliard/docker-pure-ftpd#example-usage-once-inside

Alternativly, you can start the container with a user and password setup automatically, see here:
https://github.com/stilliard/docker-pure-ftpd#setting-runtime-ftp-user

Hope this helps.

**Comment by Assafkalfa** [comment]
Really thank you, looks like I missed this section by mistake..
Thanks again!, I'll take a look (probably tomorrow..)

Assaf

**Comment by srklonaris** [comment]
Related to this - I am also having trouble connecting using a python client.

```
docker run -e FTP_USER_NAME=bob -e FTP_USER_PASS=12345 -e FTP_USER_HOME=/home/bob -e "ADDED_FLAGS=-d -d" -e FTP_PASSIVE_PORTS=10000:10009 --expose=10000-10009 --rm -d --name ftpd_server -p 21:21 -p 10000-10009:10000-10009 -p 30000-30009:30000-30009 stilliard/pure-ftpd bash /run.sh -c 30 -C 10 -l puredb:/etc/pure-ftpd/pureftpd.pdb -E -j -R -P localhost -p 30000:30059
```

```
ftp = FTP()
ftp.connect('localhost', 21)
ftp.login('bob', '12345')

filepath = 'test.csv'
ftp.storbinary(f'STOR {filepath}', open(filepath, 'rb'))
>>> ConnectionRefusedError: [Errno 61] Connection refused

```

The client is in passive mode, but wondering if i'm not configuring the server correctly

**Comment by stilliard** [comment]
Hi @srklonaris 
Ah interesting, I'm not spotting anything off with your setup, sorry that's not much help.
Maybe if you haven't already, try checking the output of `docker ps` or `docker port ftpd_server` to make sure the ports are properly listed. Also maybe check `docker logs ftpd_server` to see if anything in the log output helps point you in the right direction. I hope this was helpful.

**Comment by Assafkalfa** [comment]
Hi

I tried the commands but still not success, will be glad for some more help please.
Below is the screenshot:

![sftpConnection](https://user-images.githubusercontent.com/15208420/77999044-b9c1ba80-733a-11ea-88ed-a37877db3625.png)

I enter the sftp and create a user.
I didn't find a directory with my name in home/ftpusers
And failed to connect to the server from remote

Thank you very much !!
  Assaf

**Comment by srklonaris** [comment]
@stilliard Thanks for the quick response.  Figured it out, I was not exposing the right port range

**Comment by stilliard** [comment]
@srklonaris that's fantastic & you're welcome.

@Assafkalfa ah no worries, could you please try checking the output of `docker ps` or `docker port ftpd_server` to make sure the ports are properly listed as well as maybe checking `docker logs ftpd_server` to see if anything in the log output. If still no luck can you paste me the output from the docker logs command, thank you.

**Comment by Assafkalfa** [comment]
Thank you very much I really appreciate your patience and willingness to help!

This the log I saw in the docker:

```
Creating user...
Password:
Enter it again:
root user give /home/assaf directory ftpuser owner
Setting default port range to: 30000:30009
Setting default max clients to: 5
Setting default max connections per ip to: 5
Starting Pure-FTPd:
pure-ftpd -l puredb:/etc/pure-ftpd/pureftpd.pdb -E -j -R -P localhost -p 30000:30009 -c 5 -C 5
```

I tried localhost, assaf, my password, 30000 and 30009, still failed to connect (via fileMozila, Windows).

**Comment by stilliard** [comment]
No problem at all. 

Your setup looks good to me, I'm thinking maybe it's a firewall issue. 

Couple things to check:

1. I noticed in the screenshot your filepath is under CodeCloud? I don't know what this is but is the container running locally on your machine or on a remote/cloud machine? If remote, you'd want to use the IP instead of localhost both when starting the container and when connecting. 

2. If it's running locally on your machine, maybe it's a firewall issue? I'm not on windows so I don't know much about where this is setup sorry but it might be you need to change your internal firewall settings to allow internal connections on that port. 

Hope some of the above helps

**Comment by Assafkalfa** [comment]
@stilliard Thank you very much!
Good to know I'm OK :)
In this case CodeCloud is a local directory (meanwhile..).
I'll check the Firewall (actaully I'm working on the company laptop, maybe they block something..)

Thanks again!!
  Assaf
