### ISSUE TITLE
Crash when add FTP_PASSIVE_PORTS

### ISSUE THREAD

**Issue by quequiere** [stilliard/docker-pure-ftpd#132]
Hello,

> Got an error when I try to change passive port:
`ftpserver_1  | Creating user...
ftpserver_1  | Password:
ftpserver_1  | Enter it again: Error.
ftpserver_1  | Check that [useruser] doesn't already exist,
ftpserver_1  | and that [/etc/pure-ftpd/passwd/pureftpd.passwd.tmp] can be written.
ftpserver_1  |
ftpserver_1  |  root user give /home/useruser directory ftpuser owner
ftpserver_1  | Setting default port range to: 30010-30019
ftpserver_1  | Setting default max clients to: 5
ftpserver_1  | Setting default max connections per ip to: 5
ftpserver_1  | Starting Pure-FTPd:
ftpserver_1  |   pure-ftpd  -l puredb:/etc/pure-ftpd/pureftpd.pdb -E -j -R -P localhost   -p 30010-30019 -c 5 -C 5
formdude-second_ftpserver_1 exited with code 4294967295

Extract of my docker compose:

>  ftpserver:
    image: gists/pure-ftpd
    ports:
      - "21:21"
      - "30010-30019:30010-30019"
    expose:
      - "30010-30019"
    volumes:
      - "./data/Logs:/home/useruser/Logs"
      - "./ftppasswd:/etc/pure-ftpd/passwd"
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: useruser 
      FTP_USER_PASS: ************
      FTP_USER_HOME: /home/useruser
      FTP_PASSIVE_PORTS: 30010-30019

I have no problems until I add environment option FTP_PASSIVE_PORTS.

Could you help me ?

**Comment by stilliard** [comment]
Hi @quequiere 

Your docker compose setup looks great, but I think the ports need a colon between them instead of a dash, try the following change:

```diff
-FTP_PASSIVE_PORTS: 30010-30019
+FTP_PASSIVE_PORTS: 30010:30019
```

**Comment by quequiere** [comment]
Awsome it's working =D Thx you verry mush =)

**Comment by stilliard** [comment]
Fantastic! You're welcome, happy to help out.
