### ISSUE TITLE
Cannot change directory when using docker-compose.yml

### ISSUE THREAD

**Issue by emanuelef** [stilliard/docker-pure-ftpd#135]
Hi,
I'm using the provided docker-compose.yml in the repo.
I can log in to the ftp but not change directory:
error_perm: 550 Can't change directory to /home/username: No such file or directory

In my opinion by using the provided docker compose example everything should work out of the box without any change.

Thanks

**Comment by stilliard** [comment]
Hi @emanuelef 

I've just tested the docker-compose file we provide by default with only the "/folder_on_disk" part changed to a temp location my side. 

Works perfect for me, let's me change folders etc.

Have you changed the file?

**Comment by stilliard** [comment]
To test I started up the container with `docker-compose up` , used the ftp via the terminal with `ftp -p localhost 21` and I was into the home folder. 
I then ran `ls` to show no files/folders by default, then created a demo folder with `mkdir demo` and changed into it with `cd demo`. 

Hope this helps.

**Comment by emanuelef** [comment]
Thank you. I think I was trying to change folder using absolute path so /home/username, but I was already there!.
