### ISSUE TITLE
not working well from CLI client

### ISSUE THREAD

**Issue by changuelsami** [stilliard/docker-pure-ftpd#139]
Hi,
I can log in and change working directory, but some commands are not working : 

ftp -p -n 145.239.99.99
Connected to 145.239.99.99.
220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
220-You are user number 4 of 5 allowed.
220-Local time is now 12:52. Server port: 21.
220-This is a private system - No anonymous login
220 You will be disconnected after 15 minutes of inactivity.
ftp> user foobar myPwd
331 User foobar OK. Password required
230 OK. Current directory is /
Remote system type is UNIX.
Using binary mode to transfer files.
ftp> **ls**
227 Entering Passive Mode (127,0,0,1,117,57)
ftp: connect: **Connection refused**
ftp> 

I don't get it :( On fileZilla it works fine : I can list, upload and download, but not from CLI
PS : tests are done from a container on the same pure-ftp container's machine (same IP 145.239....)

Thanks :)

**Comment by stilliard** [comment]
Hey @changuelsami 
Double checking, are you setting the publichost env variable as that ip?

**Comment by changuelsami** [comment]
This is what I have in docker-compose.yml :
`PUBLICHOST: "localhost"`
I guess it should be like this : 
`PUBLICHOST: "145.239....."`
Right ? Only that IP ? No localhost any more ?

**Comment by stilliard** [comment]
Yep that should do it, hope it works

**Comment by changuelsami** [comment]
It works with both FileZilla and CLI, thanks :)
