### ISSUE TITLE
Put the db in a volume to make it survive reboot

### ISSUE THREAD

**Issue by KalleDK** [stilliard/docker-pure-ftpd#14]

**Comment by stilliard** [comment]
Hi @KalleDK ,
Sure you can do this in your docker run command: https://docs.docker.com/engine/userguide/dockervolumes/#mount-a-host-file-as-a-data-volume

**Comment by vingrad** [comment]
What is the path to DB?

**Comment by stilliard** [comment]
Hi @vingrad, 
I believe by default it's at /etc/pure-ftpd/pureftpd.pdb
