### ISSUE TITLE
Implict ftps

### ISSUE THREAD

**Issue by mpk166** [stilliard/docker-pure-ftpd#141]
Hi,

Is it possible to enable implicit ftps some how?

Thank you in advanced!

**Comment by stilliard** [comment]
Hi @mpk166 
I've had a quick look around and believe you'd need to edit the Dockefile, replacing `--with-tls` with `--with-implicittls`
Ref: https://serverfault.com/questions/455399/configure-pure-ftp-for-implicit-ftps
Hope this helps.
