### ISSUE TITLE
System user and group

### ISSUE THREAD

**Issue by anoma** [stilliard/docker-pure-ftpd#15]
Several suggestion in one as they are all interrelated. 

I suggest the following

```
groupadd --gid 1010 ftpgroup
useradd --uid 1011 --gid ftpgroup -d /dev/null -r -s /usr/sbin/nologin ftpuser-rw
useradd --uid 1012 --gid ftpgroup -d /dev/null -r -s /usr/sbin/nologin ftpuser-ro
```

This is different to what we do currently:
- We explicitly set UID and GID rather than implicitly trusting the OS to set it the same each build. This would be a rare edge case problem but its trivial to head off and ensure portability of the data to installs outside docker which are more likely to have users setup before pureftp.
- `-r` tells useradd that it is a system user only
- `-s /usr/sbin/nologin` is perhaps defunct with the -r switch but to be safe we use the standard means to say no shell for these users
- `-d /dev/null`  is also perhaps defunct but it ensures the user has no home directory
-  We have two users, one for read only pureftp alias accounts `ftpuser-ro` and one for accounts that can write `ftpuser-rw` (pureftp has no means to set accounts RO and relys on system acounts to do this)

**Comment by trigrab** [comment]
Maybe you could also set the uids as ENV. So that we can ensure that the permissions on the host and the one in the container match.

**Comment by anoma** [comment]
I dont know what is going wrong then. Tested successfully here on Ubuntu rather than Debian this time

```
root@ubuntu:/root# id ftpuser-rw
id: ftpuser-rw: no such user
root@ubuntu:/root# groupadd --gid 1010 ftpgroup
root@ubuntu:/root# useradd --uid 1011 --gid ftpgroup -d /dev/null -r -s /usr/sbin/nologin ftpuser-rw
root@ubuntu:/root# id ftpuser-rw
uid=1011(ftpuser-rw) gid=1010(ftpgroup) groups=1010(ftpgroup)
```

**Comment by trigrab** [comment]
I tested on debian and it wouldn't work either. I think also because of the possibility to set an environment variable, I would prefer to set this in an entrypoint.sh or something like this.

**Comment by anoma** [comment]
I am beginning to think I am incorrectly understanding what you are saying here because

```
root@debian:/# cat /etc/debian_version
8.2
root@debian:/# id ftpuser-rw
id: ftpuser-rw: no such user
root@debian:/# groupadd --gid 1010 ftpgroup
root@debian:/# useradd --uid 1011 --gid ftpgroup -d /dev/null -r -s /usr/sbin/nologin ftpuser-rw
root@debian:/# id ftpuser-rw
uid=1011(ftpuser-rw) gid=1010(ftpgroup) groups=1010(ftpgroup)
```

**Comment by trigrab** [comment]
I think so too.

What I'm trying to say is, that I don't think it has anything to do with your distro.

I think you can't change the uid in the build process. Therefore I would suggest doing it afterwards in the entryoint.

Like suggested here: https://github.com/docker/docker/issues/7198#issuecomment-158566258

**Comment by anoma** [comment]
Sorry yes I was not following.

Now that I think about it I believe I have seen this issue and solution before.

Your solution of using script with default values that can be overwritten by a ENV var would be for the best.

**Comment by stilliard** [comment]
Hi @anoma & @trigrab ,
I thought I'd write out to ask if either of you are interested in working on this project as a collaborator? 
I still use the master branch of this project but only in a basic capacity so the security improvements proposed for the hardened I don't have much time to work on lately, so if you're interested in taking over them let me know :).

**Comment by stilliard** [comment]
Closing for now as part of a cleanup of old issues but please re-open if it's still a requested feature. Thank you.
