### ISSUE TITLE
Base directory

### ISSUE THREAD

**Issue by anoma** [stilliard/docker-pure-ftpd#16]
Following on from https://github.com/stilliard/docker-pure-ftpd/issues/15 which defines two system accounts for pureftp use it starts to make little sense to place the pureftp root directory under /home/user at all.

There is a debate to be had where this data should be stored in a the traditional Linux filesystem hierarchy however in docker land I propose that it could possibly be `/ftp`.

This makes the command to volume mount this directly to the host OS if necessary shorter and probably better fits the appliance model of docker.

This change will necessitate the creation of the directory and the setting of the permissions within the dockerfile but combined with https://github.com/stilliard/docker-pure-ftpd/issues/15 allows users the power of debian system user security for RO/RW.

**Comment by felipebernardes** [comment]
+1

**Comment by stilliard** [comment]
Closing for now as part of a cleanup of old issues but please re-open if it's still a requested feature. Thank you.
