### ISSUE TITLE
Please fix docs about --tls flags "Automatic TLS certificate generation"

### ISSUE THREAD

**Issue by arkanoid87** [stilliard/docker-pure-ftpd#161]
it is not sufficient to add "--tls" to the flags, but it is necessary to add --tls=1 or 2 or 3

I know this is specified in the pure-ftpd docs, but if an user goes "quick and automatic" it doesn't want to fall into into the situation where the cert is actually generated but socket is insecure

```
-Y tls behavior
    -Y 0 (default) disables SSL/TLS security mechanisms.
    -Y 1 Accept both normal sessions and SSL/TLS ones.
    -Y 2 refuses connections that aren't using SSL/TLS security mechanisms, including anonymous ones.
    -Y 3 refuses connections that aren't using SSL/TLS security mechanisms, and refuse cleartext data channels as well.
    The server must have been compiled with SSL/TLS support and a valid certificate must be in place to accept encrypted sessions. 
```

**Comment by stilliard** [comment]
Hey @arkanoid87 
The docs on this specific part just say that they detect that flag, not an example of it, while above we do talk about examples setting this number. 

However to help make this even clearer I've added some examples in.
Thanks.
