### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by anoma** [stilliard/docker-pure-ftpd#17]
Pureftp logging by default is pretty bad. It makes no sense that a log file with a date in the filename would actually contain a mix of differnt days data most of which is the previous day. It is also is surprising to find that most of the logs contain no information to identify which host the log data came from (useless if you run more than one FTP server and they all produce identically named log files).

Unfortunately the fixes for these issues are relatively ugly.

List of known fixes so far (open to better suggestions):
- Set a random unique hostname on first start of the docker which we can use each instance to differentiate logs. This will probably require a restart of docker to take effect though.
- Change to CLF format and use the hostname in the log file name `echo "clf:/var/log/pure-ftpd/transfer-FTP-$hostn.log" > /etc/pure-ftpd/conf/AltLog`
- Make rsylog aware of this custom logging

```
   echo "" >>  /etc/rsyslog.conf
   echo "#PureFTP Custom Logging" >>  /etc/rsyslog.conf
   echo "ftp.*                           /var/log/pure-ftpd/pureftpd-FTP-$hostn.log" >>  /etc/rsyslog.conf
   echo "Updated /etc/rsyslog.conf with /var/log/pure-ftpd/pureftpd-FTP-$hostn.log"
```
- Alter logrotate to not throw away logs and make use of the recent feature of naming logs based on yesterdays date

```
cat > /etc/logrotate.d/pure-ftpd-common <<- EOM
/var/log/pure-ftpd/pureftpd-FTP-$hostn.log
/var/log/pure-ftpd/transfer-FTP-$hostn.log
{
        daily
        dateext
        dateyesterday
        missingok
        rotate 365
        compress
        postrotate
                /usr/sbin/pure-ftpd-control restart >/dev/null
        endscript
}
```
- Ugly fix `/etc/crontab cron.daily` to run at 00:01 so that logs contains predominately one day of data `sed -i "s@25 6@01 0@" /etc/crontab`
- There are other rsylsog fixes that are beyond my sed skills to fix as the config format is convoluted and multiline. Will post details once we agree a general approach.

**Comment by bluepuma77** [comment]
In general it would be great to have more logging by default. I tried with

`/usr/sbin/pure-ftpd -d -d -O stats:/var/log/pureftpd.log`

and a file `/var/log/pure-ftpd` is created with the file up-/download information.

But for valid/invalid logins or transfer problems there seems to be no log file. Directory `/var/log/pure-ftpd` exists but is empty. The Docker container log is always empty.

**Comment by stilliard** [comment]
Hey, I know this is an old ticket but finally added logging support to the container with rsyslog. 
Closing this issue for now, but please reopen if any changes are wanted :).
