### ISSUE TITLE
Possilble to access with SFTP aka with ssh-key file instead of user+password?

### ISSUE THREAD

**Issue by namgivu** [stilliard/docker-pure-ftpd#172]
I'm looking for FTP server that can serve with SFTP protocol using SSH key, is it possible? If yes, please guide us how to. 

I have go thru the walkthru [here](https://github.com/stilliard/docker-pure-ftpd/wiki/Basic-example-walk-through) and it seems to serve with user+password only.

Cheers

**Comment by namgivu** [comment]
We may interest using https://github.com/atmoz/sftp

**Comment by stilliard** [comment]
Pure-FTPd provides FTP & FTPS (FTP+SSL) support which works for most cases. 
For SFTP support you'd need to use a dedicated SFTP service instead such as the one you mentioned :)
Hope this helps clarify.
