### ISSUE TITLE
TLS mode 2 and i can connect whit filezilla in plain mode

### ISSUE THREAD

**Issue by rodriciru** [stilliard/docker-pure-ftpd#179]
I have configure TLS option 2, so i understand that Filezilla shoul not been able to connect in plain mode, but i can. Also with WinSCP

Also i can connect in secure mode also.

What im doing wrong?

```
TLS                          2
CertFile                     /etc/ssl/private/pure-ftpd.pem
```

**Comment by rodriciru** [comment]
ok. i was missing ADDED_FLAGS --tls=2.
But whats the point of set in config file if the will ignore them?

**Comment by stilliard** [comment]
Hi @rodriciru 
What config file are you setting these in? Is it a docker compose file or similar?

**Comment by rodriciru** [comment]
I use docker-compose to run httpd, pure-ftpd,mariadb....
Bu the option TLS numbre 2 i try to put in pure-ftpd.conf and in conf/TLS whitout any success
Only setting in compose file make it works

**Comment by stilliard** [comment]
Hi @rodriciru 

Ah ok cool, docker compose way is the way to go here, the pure-ftpd.conf files isn't something created or used by this docker image project. 

The [readme](https://github.com/stilliard/docker-pure-ftpd#readme) lists all available env var based conf you can use and we also support all pure-ftpd flags via ADDED_FLAGS ref https://linux.die.net/man/8/pure-ftpd

Hope this helps.
