### ISSUE TITLE
Auth log and error log

### ISSUE THREAD

**Issue by alessiofx** [stilliard/docker-pure-ftpd#18]
How to watch the log of ftp server ?

Thanks

**Comment by stilliard** [comment]
Hey @alessiofx , sorry for my late reply on this. 
I'm not sure if the default setup we have in this container sets a log up but i believe you can pass one as a flag when starting pure-ftpd.
Adding something like ` -O stats:/var/log/pureftpd.log` should work.
Then you could use `docker exec` to run `tail -f` of that log to watch it live. 
I hope this helps.

**Comment by boistordu** [comment]
I still have problem too 
ECONNREFUSED

**Comment by stilliard** [comment]
@boistordu, could you please open a new ticket with more information on your issue, thank you
