### ISSUE TITLE
FTPs (TLS) causing the connection to throw connection error

### ISSUE THREAD

**Issue by anupshah2it** [stilliard/docker-pure-ftpd#180]
Error: I won't open a connection to 127.0.0.1 (only to 172.20.0.1) (code=500)

My docker file is as below, I have tried passive ports range too but not sure about --expose here, I am able to connect at first through my code but at a second attempt or reusing it is throwing the above error. 

I understand it has something with the passive mode but I have the configuration but not sure what is missing, please help.  

`version: '3'

services:
  ftpd_server:
    image: stilliard/pure-ftpd
    container_name: pure-ftpd
    privileged: true
    ports:
      - "21:21"
      - "30000-30099:30000-30099"
    volumes: # remember to replace /folder_on_disk/ with the path to where you want to store the files on the host machine
      #- "/tmp/test/data:/home/username/"
      #- "/tmp/test/passwd:/etc/pure-ftpd/passwd"
      - "/upload:/home/upload"
      #- "./certs:/etc/ssl/private"
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: lktransfer
      FTP_USER_PASS: lktransfer
      FTP_USER_HOME: /home/upload/
      #FTP_PASSIVE_PORTS: "30000-30009"
      FTP_MAX_CLIENTS: 50
      FTP_PASSIVE_PORTS: 30000:30099
      FTP_MAX_CONNECTIONS: 50
      ADDED_FLAGS: "--tls=1"
      #ADDED_FLAGS: "--tls=2"
      TLS_USE_DSAPRAM: "true"
      TLS_CN: "localhost"
      TLS_ORG: "Ellkay"
      TLS_C: "IN"
    restart: always`

**Comment by stilliard** [comment]
Hi @anupshah2it 
Sorry for the delayed reply.
How are you connecting via FTP, in the your FTP client are you using passive mode?

**Comment by anupshah2it** [comment]
Well, thanks for your reply. 

I am able to connect it too, also have removed privileged tags and others, and yes it was connecting thru Active mode hence was an issue but is now resolved.

**Comment by stilliard** [comment]
That's great, glad it's all ok now, thanks for the update :+1:
