### ISSUE TITLE
[SOLVED] (not an error) 550 Can't check for file existence 

### ISSUE THREAD

**Issue by Tuumke** [stilliard/docker-pure-ftpd#185]
I haven recently installed your docker, which is working great! Great speeds, easy setup. But when i am uploading, i keep getting:

```
[11:46:40] Upload: file.jpg 12 KB in 0.02 seconds (12.3 KB/s)
[11:46:40] [R] MFMT 20220921202419 /path/file.jpg
[11:46:40] [R] 213 UTIME OK
[11:46:40] [R] MLST file.txt
[11:46:40] [R] 550 Can't check for file existence

```

I have 2 folders extra mounted via 

```
    volumes: 
      - "$DOCKERDIR/pure-ftpd/home:/home/user/"
      - "$DOCKERDIR/pure-ftpd/passwd:/etc/pure-ftpd/passwd"
      - "/mnt/user/folder1:/home/user/folder1"
      - "/mnt/user/folder2:/home/user/folder2"
```

They are owned by dockers:users Docker is also running under same user+group..

```
drwxrwxrwx  1 dockers users 4.0K Sep 22 13:08 folder1/
drwxrwxrwx  1 dockers users    6 Sep 23 01:35 folder2/
drwxr-xr-x  1 nobody  users    6 Sep 18 11:25 pure-ftpd/
```

Where do i start looking where this is comming from? Saw something about pure-ftpd not being configured for FXP, but i'm just straight connected. Not FTP <-> FTP..

**Comment by stilliard** [comment]
Hi @Tuumke 
Hmm weird, are you able to download the files all fine?

**Comment by stilliard** [comment]
If FXP is maybe the issue, you could try passing the `--allowuserfxp` flag via the `ADDED_FLAGS` env var (ref https://github.com/stilliard/docker-pure-ftpd#starting-it)
Hope this helps

**Comment by Tuumke** [comment]
> Hi @Tuumke Hmm weird, are you able to download the files all fine?

Yes, all works fine (up and download).



> If FXP is maybe the issue, you could try passing the `--allowuserfxp` flag via the `ADDED_FLAGS` env var (ref https://github.com/stilliard/docker-pure-ftpd#starting-it) Hope this helps

Hm doesn't seem to be sovling it :(
I've also read we could ignore this error, but i prefer to solve them instead of ignoring errors :P

**Comment by stilliard** [comment]
Weird, glad it works fine but yeah I'm with you that it's best to solve the errors so you can see real errors later down the line easier as well. 

One thing to check, what FTP client are you using atm? 
Could you try a different one such as Filezilla to see if it's an issue with how that FTP client is talking to the server?

**Comment by Tuumke** [comment]
> Weird, glad it works fine but yeah I'm with you that it's best to solve the errors so you can see real errors later down the line easier as well.
> 
> One thing to check, what FTP client are you using atm? Could you try a different one such as Filezilla to see if it's an issue with how that FTP client is talking to the server?

Ah smart idea! I'm using FlashFXP (been using it for years, love the ability to que things and easily resume). Will try FileZilla

**Comment by Tuumke** [comment]
@stilliard seems to be the client?

```
Command:	TYPE I
Response:	200 TYPE is now 8-bit binary
Command:	PASV
Response:	227 Entering Passive Mode (w.x,y,z,117,53)
Command:	MLSD
Response:	150 Accepted data connection
Response:	226-Options: -a -l 
Response:	226 7 matches total
```

You got any more ideas on what kind of FTP setting this is?

**Comment by stilliard** [comment]
Ah awesome, that's great it works ok with Filezilla though to resolve with FlashFXP I wonder if you can switch it to use MLSD instead?

**Comment by stilliard** [comment]
Hi @Tuumke , I've found this which may work:
https://www.flashfxp.com/forum/15781/p82128-post4.html (ref https://www.flashfxp.com/forum/flashfxp/general-discussion/15781-550-filename-ext-cannot-listed.html)

**Comment by Tuumke** [comment]
Yeah i'm.. trying to find out where. Weird thing is that MLST file.txt after upload works just fine.
I'm now thinking it sending an MLST file.ext to check IF the file already exists.

**Comment by Tuumke** [comment]
Thanks, see reply above. I just guessed that as well seeing as the command is made prior to STOR

```
[R] MLST edit_active_auction.php   --> CHECK FOR EXISTENCE
[R] 550 'edit_active_auction.php' cannot be listed --> RESPONSE FILE DOESNT EXIST
[R] PASV --> GO PASSIVE CMD
[R] 227 Entering Passive Mode (217,xx,x,xxx,138,33). --> RESPONSE
[R] Opening data connection IP: 217.xx.x.xx PORT: 35361 --> GET READY TO STORE
[R] STOR edit_active_auction.php --> STORE FILE
```

Thank you so much for helping me figure this out :-)

**Comment by stilliard** [comment]
Perfect! Glad you tracked that down. 
I'll close this off now but it'll be left around for anyone else to see in case they run into the same issue in the future too thanks.
