### ISSUE TITLE
Slow transfert speed

### ISSUE THREAD

**Issue by hermann-osi** [stilliard/docker-pure-ftpd#190]
Hello,
I have just installed the hardened version using docker-compose but with the first test, the transferts are pretty slow : 300kB/s instead of 100 MB/s. Does somebody knows if there is a setting to modify or if it's a real issue ?

Also I can't find any logs inside the container at /var/logs. Are they somewhere else or is it possible to activate them ?

Thank you in advance

**Comment by stilliard** [comment]
Hi @hermann-osi 

Hmm, transfer speeds can be a little slow but I'd try the `latest` version instead and see if that improves anything. 
If it does improve, you can find a list of flag changes the `hardened` version contains here: https://github.com/stilliard/docker-pure-ftpd/compare/master..hardened *(ignore the documentation typo change missing from the hardened version atm)*

For logging you'll need to enable this during the `docker run` command, more info available on this here: https://github.com/stilliard/docker-pure-ftpd?tab=readme-ov-file#logs

Hope this helps.

**Comment by hermann-osi** [comment]
Thank you, 
After more investigating, the issue is with the network of the server and not the docker image.

**Comment by stilliard** [comment]
Ah awesome, glad you solved it! :+1:
