### ISSUE TITLE
Annon Access help

### ISSUE THREAD

**Issue by lukedoesgit** [stilliard/docker-pure-ftpd#191]
Hi, thanks for the great work :)

I set everything up and could add users and login in to local host via filezilla.

However now i would just like annon users i have followed mostly from the issue 144 and 43

i have omitted the env vars from my compose file and changed the run.sh file to use annon user , however im not sure if/how i can use the run command and the -e flag as currently i use a profile to bring all my containers up. (Is this what is stopping annon access from working ?)

currently getting this error in file zilla 

![image](https://github.com/stilliard/docker-pure-ftpd/assets/164025980/0dc14a20-8941-4f55-a914-dea9c679c74a)

Any suggestions or pointers in right direction would be great as i am new to this 

Thanks in advance

**Comment by lukedoesgit** [comment]
UPDATE:

I found this at the bottom of the dockerfile would removing -E from here be the same ? 

![image](https://github.com/stilliard/docker-pure-ftpd/assets/164025980/fb2e8205-99bb-46b0-bdf9-223dab3eff44)

**Comment by stilliard** [comment]
Hi Luke,

I've not done much with anon logins with ftp but I'll help where I can. 

In your update you mentioned the Dockerfile `CMD` line which is where we pass `-E` to prevent anon ftp access by default (ref https://linux.die.net/man/8/pure-ftpd). 
Yes you're right that you'll either need to remove that, or you could maybe override it by setting/overriding the `command` directly in your docker-compse file (ref
https://docs.docker.com/compose/compose-file/compose-file-v3/#command)

Hope this helps but if not, if you can provide an example docker-compose file or changes made I can have a go my side later today.

**Comment by stilliard** [comment]
Also, not sure if this helps or if you've seen but another user here did start work on anon support directly for the project but it wasn't finished: https://github.com/stilliard/docker-pure-ftpd/pull/152/files

**Comment by lukedoesgit** [comment]
> Also, not sure if this helps or if you've seen but another user here did start work on anon support directly for the project but it wasn't finished: https://github.com/stilliard/docker-pure-ftpd/pull/152/files

Hi Stilliard,

Thanks for confirming the removal of the -E flag , it now allows me to login as an annon user. And yes i started following that page too which was helpful.

Thanks again !

Luke
