### ISSUE TITLE
error logging 

### ISSUE THREAD

**Issue by boistordu** [stilliard/docker-pure-ftpd#22]
the -o as modification in the launch command in the dockerfile doesn't work by the way... So I do'nt have any log for verify the problem. But I have some Ideas I will try that first... can you just watch the -0 option?

**Comment by stilliard** [comment]
Hey @boistordu, logging support is a bit weird with pureftp here (https://github.com/stilliard/docker-pure-ftpd/issues/17) but to test can you send me the command's you're using? e.g. docker run etc. Thanks

**Comment by boistordu** [comment]
I don't understand why the internal widnows server 2016 firewall was blocking it but it seems okey now. I guess there is no option activated beside the passive mode in your ocnfiguration?

**Comment by stilliard** [comment]
Not sure either sorry about the firewall issue, you could check to see if it was blocking some of the needed ports, 21 & 30000 through to 30009. 
I haven't had success with active mode on here sorry, I'll try a few ideas later but not sure if it'll work. But if you get it working please let me know and I can update the docs or you can submit a pull request for t. Thanks.

**Comment by stilliard** [comment]
Actually, ignore my last message, Active mode should work fine. Just tried via Filezilla and it seems to work well. Hope this helps

**Comment by stilliard** [comment]
Hi @boistordu , Just following up to check if you had any more firewall issues with the container since this? If not I'll close off this ticket, thanks.
