### ISSUE TITLE
PASV ftp: connect: Connection refused

### ISSUE THREAD

**Issue by huzorro** [stilliard/docker-pure-ftpd#25]
I configured  pure-ftpd config file with these params :
PassivePortRange  49152 65534
ForcePassiveIP LINODE_SERVER_PUBLIC_IP

ftp -p LINODE_SERVER_PUBLIC_IP
Connected to LINODE_SERVER_PUBLIC_IP.

220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
220-You are user number 1 of 50 allowed.
220-Local time is now 03:47. Server port: 21.
220-This is a private system - No anonymous login
220 You will be disconnected after 15 minutes of inactivity.
Name (LINODE_SERVER_PUBLIC_IP:xxxx): sjzzt007
331 User sjzzt007 OK. Password required
Password:
230 OK. Current directory is /
Remote system type is UNIX.
Using binary mode to transfer files.
ftp> ls
227 Entering Passive Mode (LINODE_SERVER_PUBLIC_IP,156,200)
ftp: connect: Connection refused

**Comment by stilliard** [comment]
Hi @huzorro ,
I'm wondering if the config file isn't being loaded in? 
Could you try passing the PUBLICHOST env variable during docker run and set this to be your LINODE_SERVER_PUBLIC_IP? 
Hope this helps.

**Comment by stilliard** [comment]
Closing for now, but please re-open or open a new ticket if you're still experiencing any issues thanks.

**Comment by zakariazouaoui** [comment]
i have the same issue and i don't know ho to solve it any ideas ?

**Comment by stilliard** [comment]
@zakariazouaoui are you setting the PUBLICHOST as the ip/host you're using to connect in with?

**Comment by zakariazouaoui** [comment]
yes i am using iton my server here is my docker-compose file 

services:
  ftpd_server:
    image: stilliard/pure-ftpd
    ports:
      - "60072:21"
      - "60073-60081:30000-30009"
    volumes:
     - ./data/ftpserver/ftp:/home/socrat/
     - ./data/ftpserver/passwd:/etc/pure-ftpd/passwd
    environment:
      PUBLICHOST: "myserver.com" 
      FTP_USER_NAME: "test"
      FTP_USER_PASS: "test"
      FTP_USER_HOME: "/home/test"
      ADDED_FLAGS: " -d -d" 
    restart: always
    networks:
      network:
        ipv4_address: 192.177.0.8

**Comment by stilliard** [comment]
Worth trying it as the ip you have there of 192.177.0.8

**Comment by zakariazouaoui** [comment]
here is the output 

Connected to myserver.com.
220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
220-You are user number 1 of 5 allowed.
220-Local time is now 14:26. Server port: 21.
220-This is a private system - No anonymous login
220-IPv6 connections are also welcome on this server.
220 You will be disconnected after 15 minutes of inactivity.
Name (mywebsite.com:ubuntu): test
331 User testOK. Password required
Password:
230 OK. Current directory is /
Remote system type is UNIX.
Using binary mode to transfer files.
ftp> ls
227 Entering Passive Mode (192,177,0,8,117,48)


but nothing else

**Comment by brett-spaulding** [comment]
I'm experiencing the same issue; was this ever resolved?
Just trying to run this on my local machine via docker-compose and access FTP on localhost

230 OK. Current directory is /
Remote system type is UNIX.
Using binary mode to transfer files.
ftp> ls
227 Entering Passive Mode (127,0,0,1,136,189)
ftp: connect: Connection refused
