### ISSUE TITLE
SSL/TLS ENV in Dockerfile

### ISSUE THREAD

**Issue by NicoAiko** [stilliard/docker-pure-ftpd#27]
When activating TLS/SSL, I personally wanted to disable non-tls connections.
But to do this, I had to completely build the docker myself after git cloning it and modify the run.sh.

Therefore I suggest, you implement an environment variable for personal interest and maybe a default value, when not set.

**Comment by stilliard** [comment]
Hi @NicoAiko ,
Sounds interesting, would you be interested to make a pull request for this?

**Comment by NicoAiko** [comment]
Of course!
Right now, I'm testing the modified Dockerfile and run.sh.

**Comment by stilliard** [comment]
Hey @NicoAiko , I've built a new change inspired by your pull request :). 
You can now pass ADDED_FLAGS as a docker env var which allows you to set and override the --tls flag. 
Thanks again for pointing out the need for this!
