### ISSUE TITLE
python ftplib failed with port different than 21

### ISSUE THREAD

**Issue by drorbar** [stilliard/docker-pure-ftpd#29]
Hi, 

I'm having some trouble connecting to the docker with python ftplib.
I've tried to run the docker with -p 2221:21 which worked and when I create the connection using the FTP command line everything works great.
When using python lib ftplib to create connection it worked but as soon as I try to download a file or run dir the entire python get stuck and no more packets are running from the client or the server.\
Is there any explanation for this behavior? 

Just to be clear, if I create the docker with -p 21:21 everything work with the python lib.

Thanks

**Comment by stilliard** [comment]
Hi @drorbar ,
That's a bit weird, I'd expect it to be the same. 
Could you paste me some example code you have using the python ftplib to test with?
Thanks

**Comment by drorbar** [comment]
Ok, kept working on that.
Removed all old container and images from my localhost and that seemed to work.
Tried on the server and after changing the -e worked :)

**Comment by stilliard** [comment]
Ah awesome, glad it's working for you now :+1:
