### ISSUE TITLE
Running in a not daemon way

### ISSUE THREAD

**Issue by kluthen** [stilliard/docker-pure-ftpd#3]
I was wondering if there was some built in way to have it running in foreground instead ? 
Otherwise I'll manage one
Thanks !

**Comment by stilliard** [comment]
Hi @kluthen ,
That's a great idea, now that docker has "docker exec" we can stop it from starting the bash process in the foreground and enter the container with bash via docker exec.
I can work on this later, but feel free to open a pull request now if you'd like?

**Comment by kluthen** [comment]
I must say I don’t know much about the whole thing (docker, pure-ftp …) 
I’ll try to have it run foreground, if I succeed i’ll keep you informed :)

As for the usage, it was mostly to have it supervised by systemd ^^

Thanks for your quick reply !

Bastien

**Comment by kluthen** [comment]
Ah, how devious of you ;)

CMD /usr/sbin/pure-ftpd -c 30 -C 1 -l puredb:/etc/pure-ftpd/pureftpd.pdb -x -E -j -R &\
	/bin/bash

Guess that explains it :p

I’ll try without if it runs nicely enough
