### ISSUE TITLE
Image too big

### ISSUE THREAD

**Issue by ndobromirov** [stilliard/docker-pure-ftpd#30]
Check the recommendations for handling layers in the images.
Try to reduce the size of the image by combining layers and doing clean up in the end of each.
Remove APT cache, temporary directories, source files (needed only for compilation), *-dev packages, also needed only for compilation.

**Comment by stilliard** [comment]
Hi @ndobromirov! Feel free to make a pull request with some suggestions thanks. 
I'm more than happy for some optimisations to be made, though I also don't want the Dockerfile coming out overly complex in the pursuit of smaller disk size.

**Comment by stilliard** [comment]
Closing for now but feel free to open a pull request or share some ideas any time thanks.
