### ISSUE TITLE
Error connecting using a ftp client

### ISSUE THREAD

**Issue by sebfie** [stilliard/docker-pure-ftpd#31]
Hello,

I used this docker and it works great. I mean, I can connect using command line but when I use a real ftp client, I have error like : 
- 113 : Passive mode failed
- Very long time before to connect...

I also have limit to 5 connections : 

```
$ ftp 192.168.99.100
Connected to 192.168.99.100.
220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
220-You are user number 2 of 5 allowed.
220-Local time is now 10:28. Server port: 21.
220-This is a private system - No anonymous login
220-IPv6 connections are also welcome on this server.
220 You will be disconnected after 15 minutes of inactivity.
```

In my docker-composer I have : 

```
ftp:
  image: stilliard/pure-ftpd:latest
  env_file: docker/ftp.env
  ports:
    - "21:21"
    - "30000-30009:30000-30009"
  volumes:
    - ./ftp:/home/ftpusers/bob
    - ./vsftpd:/etc/pure-ftpd/passwd
```

ps aux on machine give me : 

> /bin/sh -c /run.sh -c 50 -C 10 -l puredb:/etc/pure-ftpd/pureftpd.pdb -E -j -R -P $PUBLICHOST -p 30000:30009

Any idea?

**Comment by sebfie** [comment]
In fact, if I do not use passive mode, it works great

**Comment by stilliard** [comment]
Hi @sebfie, glad you've got it working without passive mode for now. 
One thing that might help, you could check in your docker/ftp.env file that PUBLICHOST is set?

**Comment by sebfie** [comment]
Yes, to 127.0.0.1

Thx

Sébastien fieloux
0698458781
sebastien.fieloux@gmail.com
http://www.sebfie.com

**Comment by sebfie** [comment]
Do you reproduce it? I use transmit https://panic.com/transmit/

**Comment by stilliard** [comment]
Hi @sebfie , 
I haven't tried transmit sorry, but I'm able to connect with Filezilla. 
Would you be able to try with Filezilla just to check if there's maybe an issue with something maybe Transmit requires from us? thanks

**Comment by stilliard** [comment]
Ah I have another idea, in your `ftp` command above you're connecting to 192.168.99.100, is this what you're using in Transmit? Could you try with 127.0.0.1 instead to see if this maybe works?

**Comment by sebfie** [comment]
In fact i have a docker machine (on virtualbox) for dockers components. 

Its ip is 192.168.99.100

I will try fillezilla

Sébastien fieloux
0698458781
sebastien.fieloux@gmail.com
http://www.sebfie.com

**Comment by stilliard** [comment]
ah that's cool, in which case could you try setting the PUBLICHOST as 192.168.99.100 ?

**Comment by sebfie** [comment]
So, filezilla does not work like transmit.

But set PUBLICHOST to 192.168.99.100 make both works

**Comment by stilliard** [comment]
That's great news, looks like Passive mode requires the same IP or a domain name that points to the same IP like this.

**Comment by sebfie** [comment]
Yes, but it's an issue because with docker composer : 
- I create an ftp
- I have a rails app connecting to this ftp

I do not know the ip address of the ftp container, so I can not connect to it using passive mode.

For exemple, ftp container has 172.17.0.4 as ip, so I have to set PUBLICHOST = 172.17.0.4 ?

Do you understand?

**Comment by stilliard** [comment]
I see, but wont you need to know the IP in order to connect with ftp anyway? 

Alternatively you could connect with Active mode instead of Passive. 
Or maybe you could use a host name to handle the IP's for you?

**Comment by sebfie** [comment]
In production I use passive mode, so I want to use it with docker.

I tried that : 

PUBLICHOST=ftp.myhost.com

And on a linked container in `/etc/hosts`
- 172.17.0.4     ftp.myhost.com

And I can not connect using passive mode.

**Comment by sebfie** [comment]
Using PUBLICHOST=127.0.0.1, I can not connect in active mode, just passive...

**Comment by stilliard** [comment]
Hi @sebfie , Sorry i disappeared from this for a long time. 
Did you get much further with this?

**Comment by sebfie** [comment]
Yes! I used an other repo :)

**Comment by stilliard** [comment]
Ah that's awesome :)

**Comment by jeffmess** [comment]
@sebfie I have the exact same issue. Deploying docker-compose into production and needing to know the PublicHost ip which is a docker container IP address. Which repo did you use to resolve the problem?

**Comment by sebfie** [comment]
I used : panubo/vsftpd with this in docker-composer.yml 

```
ftp:
  image: panubo/vsftpd
  env_file: docker/env/ftp.env
  ports:
    - "21:21"
    - "4559-4564:4559-4564"
  volumes:
    - ./docker/volumes/ftp/merx:/srv/merx/
    - ./docker/volumes/ftp/wms:/srv/wms/
```

And env variables : 

```
FTP_USERS_ROOT=true
# MEMO user:password
# merx:merx123
# wms:wms123
FTP_USER_MERX=merx:$6$gwdQiyuQuzB41DbD$J7BW39vYKFSN/5WJs2HQnE/3WAOu5u6EzyRM9jcS4VERSlzhnQhyKEHoskRdmN4Jjc/aDiMmULdZCEuzIvZfW.
FTP_USER_WMS=wms:$6$QTQwUO./5AigEyIh$51BGc7ELBVoxbtvmdyfrCvB2VhGm/OfxMM6IJWPyFcBtaFwfoTT1l1nwcWVBh2BIz4giZBfX8z/zMTxHpwV3t/
```

**Comment by jeffmess** [comment]
Works, thanks.
