### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by piosk7** [stilliard/docker-pure-ftpd#32]
What's the license of this project? There is no LICENSE file, nor license in description.

**Comment by stilliard** [comment]
Thanks @piosk7 , it's MIT, i'll add the file no.

**Comment by piosk7** [comment]
Wow, thanks for such a quick reply and LICENSE file addition! 😄
And thanks for such a good docker FTP server solution.

**Comment by stilliard** [comment]
No problem, just good timing as I happened to be looking through the other issues on here when your message came in. 
Glad it works well for you.
