### ISSUE TITLE
Cannot list directory

### ISSUE THREAD

**Issue by yudao** [stilliard/docker-pure-ftpd#33]
Hi,

I'm testing your docker image and I'm facing off a problem.

If I use ftp in command line I can send a file with my virtual user. But when I'm trying to use a GUI tool (filezilla, Winscp, CyberDuck, ...) I have always the error "Cannot list directory" that turn into a timeout error after 20 seconds, but I can see the user is logged in.

The only thing I've changed is the home directory which is not in /home/username. I've set the rights. IpTable show me ACCEPT on each ports (21 and 3000/3009).

Do you have an idea why I can't list directory?

Thanks a lot and great job!

Yu.

**Comment by stilliard** [comment]
Hi @yudao ,
Sorry it's playing up for you atm. 
It may be you need to try switching between Active & Passive mode and see if that fixes it?

Alternatively, would you mind pasting me the docker run command you're using? Or part of the docker compose file if you're using that?
Then I'll test my side with the same setup, thanks.

**Comment by yudao** [comment]
Hi @stilliard,

Thanks for your quick reply!

I've already tested active and passive mode and I've got the same result.

This is my docker run command:
```sh
docker run -d --name FTP -p 21:21 -p 30000-30009:30000-30009 -v /var/lib/dokku/data/storage/ftp:/home/ftpusers -v /var/lib/dokku/data/storage/pureftp/:/etc/pure-ftpd stilliard/pure-ftpd
```

Yu.

**Comment by stilliard** [comment]
Thanks, I've quickly checked and I can connect in active mode but not passive with your command. 
But to fix passive mode all you need to do is add `-e "PUBLICHOST=localhost" ` inside the docker run command. 
You'll want to replace `localhost` in that with either the IP or Hostname you're connect on. 

Your end docker run command would then be:
```bash
docker run -d --name FTP -e "PUBLICHOST=localhost -p 21:21 -p 30000-30009:30000-30009 -v /var/lib/dokku/data/storage/ftp:/home/ftpusers -v /var/lib/dokku/data/storage/pureftp/:/etc/pure-ftpd stilliard/pure-ftpd
```
Hope this works for you too.

**Comment by yudao** [comment]
@stilliard thanks for your time and quick replies, awesome!

All is fine now!

Best regards,

Yu.
