### ISSUE TITLE
service not available

### ISSUE THREAD

**Issue by kukoman** [stilliard/docker-pure-ftpd#36]
Hi Guys, 

First, thanks for this fantastic container and all your hard work. 

I followed the guide, tried to run in as hardened, latest, build my own image, added the user, but when I try to ftp and list folders I get error 421 Service not available. 

Maybe you can help me to troubleshoot the problem? 

Commands I run on t2.medium AWS node (all ports open for my IP):
```
docker pull stilliard/pure-ftpd:hardened
docker run -d --name ftpd_server -p 21:21 -p 30000-30009:30000-30009 -e "PUBLICHOST=localhost" stilliard/pure-ftpd:hardened
docker exec -it ftpd_server /bin/bash
pure-pw useradd bob -f /etc/pure-ftpd/passwd/pureftpd.passwd -m -u ftpuser -d /home/ftpusers/bob

```
out of the container:
`ftp -p IP 21`
response:
```
gjanak@CSD006446-D:~$ ftp -p IP
Connected to IP.
220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
220-You are user number 1 of 5 allowed.
220-Local time is now 13:40. Server port: 21.
220-This is a private system - No anonymous login
220-IPv6 connections are also welcome on this server.
220 You will be disconnected after 15 minutes of inactivity.
Name (IP:gjanak): xxx
331 User xxx OK. Password required
Password:
230 OK. Current directory is /
Remote system type is UNIX.
Using binary mode to transfer files.
ftp> mdir test
(local-file) test
output to local-file: test? 
227 Entering Passive Mode (34,251,145,53,117,48)
**421 Service not available, remote server has closed connection**
ftp> 
```

Any help is much appreciated.

Thanks

**Comment by stilliard** [comment]
Thanks @kukoman!

I need to improve the docs around this, but all you should need to do is replace localhost in your code with the IP.

**Comment by kukoman** [comment]
ok, it is working from the node itself, so it must be something with the localhost

**Comment by kukoman** [comment]
:D thanks for the answer, our messages just crossed :) will try the suggestions

**Comment by stilliard** [comment]
Aha no worries, hope it works for you.

**Comment by kukoman** [comment]
works like charm :) stupid me :) thanks for your help

**Comment by stilliard** [comment]
Happy to help out, i'll improve the docs around this soon too!

**Comment by kukoman** [comment]
maybe last question, when I add the -e "ADDED_FLAGS=--tls=2" the container terminates, any words of wisdom?

**Comment by kukoman** [comment]
look at the run.sh, both flags are required tls + log
