### ISSUE TITLE
running pure-ftpd with tls

### ISSUE THREAD

**Issue by kukoman** [stilliard/docker-pure-ftpd#37]
Hi Guys,

I'm trying to start the container with the tls flag but for some reason the container terminates on start. Here's what I'm doing; I build my own image, add passwords, *.pem files and run:
```
#Dockerfile
FROM stilliard/pure-ftpd:hardened

RUN mkdir -p /etc/ssl/private
RUN rm -rf /etc/pure-ftpd/passwd/*
ADD private/* /etc/ssl/private/
ADD passwd/* /etc/pure-ftpd/passwd/
RUN chmod 600 /etc/ssl/private/*.pem

# e.g. you could change the defult command run:
CMD /run.sh -c 30 -C 5 -l puredb:/etc/pure-ftpd/pureftpd.pdb -E -j -R #-tls 1
```
Build:
```docker build -t gag-ftpd-server:latest .```
Run:
```docker run -d --name ftpd_server6 -e "PUBLICHOST=localhost" gag-ftpd-server```
So far so good

Now when I add the -tls flag in the Dockerfile:
```CMD /run.sh -c 30 -C 5 -l puredb:/etc/pure-ftpd/pureftpd.pdb -E -j -R -tls 1```
The container terminates with no logs (docker logs [container]).

I can run it with environmental variable "-e "ADDED_FLAGS=--tls=2", omitting the -tls 1 flag and it starts but doesn't work. I was wondering if you could help me to understand why it's not working with the -tls 1 flag or what am I doing wrong.

Any words of wisdom? 

Thank you.

**Comment by kukoman** [comment]
my "solution" was to leave that run sh command, then everything works as expected, but I would still appreciate if anyone more experienced could explain why it is not working with the sh script

**Comment by stilliard** [comment]
Hey @kukoman ,
Thanks for reporting this, when you start the container it should print "Starting Pure-FTPd:" and then the command and flags used, would you mind pasting them here for me to see if anything looks weird with them? thanks

**Comment by stilliard** [comment]
Closing for now, but please let me know if the issue persists and if any errors show in the docker log for this, thank you.
