### ISSUE TITLE
Maximum users 5

### ISSUE THREAD

**Issue by hmeerlo** [stilliard/docker-pure-ftpd#40]
Even though the ftp daemon is started like this:

```
root@prd-dvm-001:~# docker logs ftpd_server
Log enabled, see /var/log/messages
Starting Pure-FTPd:
  pure-ftpd -c 50 -C 10 -l puredb:/etc/pure-ftpd/pureftpd.pdb -E -j -R -P viveo2.com -p 30000:30009 -d
```

When I connect it tells me the maximum clients is 5:
```
14:18 $ ftp xxx@yyy.com
Connected to yyy.com.
220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
220-You are user number 1 of 5 allowed.
220-Local time is now 12:18. Server port: 21.
220-This is a private system - No anonymous login
220-IPv6 connections are also welcome on this server.
220 You will be disconnected after 15 minutes of inactivity.
331 User devicelog OK. Password required
Password:
230 OK. Current directory is /
Remote system type is UNIX.
Using binary mode to transfer files.
ftp> ^D
```

Any idea what is wrong here?

**Comment by fwi** [comment]
I just ran into the same problem, it is explained here:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=704260

In short: pure-ftp "reserves" 2 passive ports per user (even if they are not used). So if you want to allow 50 users, set ` -p 30000:30100`. Also I added `-y 0:0` which disables the `peruserlimits`. I could not find any default values for the `peruserlimits` (or find out if this feature was enabled - it is a compile option) so the `-y` option might not be needed.

**Comment by hmeerlo** [comment]
Yes can confirm this. I would definitely expect a huge warning telling me that my passive port range conflicts with the maximum clients settings.

**Comment by stilliard** [comment]
Thanks @fwi!
If either you or @hmeerlo would like, you can submit a pull request to add this to the README? 
Otherwise I'll find some time later today to add it in :+1: .

**Comment by sebastianhaberey** [comment]
Wow I debugged my application for _ages_ to find out where the FTP connection leak is. Turns out "maxclientsnumber" of 20 means maximum number of clients is 10. That's not great. The  documentation for `maxclientsnumber` doesn't even mention that:

> Allow a maximum of clients to be connected. For instance '-c 42' will limit access to simultaneous 42 clients. There is a 50 client limit by default.
