### ISSUE TITLE
Need help allowing anonymous read access

### ISSUE THREAD

**Issue by ipetepete** [stilliard/docker-pure-ftpd#43]
I've searched for what I'm missing but I can't seem to get the build to allow anonymous access.

I've removed the -E flag, and even changed the /etc/pure-ftpd/conf/NoAnonymous but nothing seems to allow anonymous.

Response is always error 421 

What do I need to do to allow anonymous user access?

**Comment by stilliard** [comment]
Hi @ipetepete ,
Sorry for not replying sooner. 
I believe to add anon support you must add a user called ftp and create it's home folder like so:

```bash
useradd -d /var/ftp -s /sbin/nologin ftp
mkdir /var/ftp
```

Hope this helps.
