### ISSUE TITLE
Increase allowed connections

### ISSUE THREAD

**Issue by deathcoder** [stilliard/docker-pure-ftpd#46]
Hi from the documentation it says that overriding the command allows to increase the maximum connections, i tried it and initially didn't work, i looked around a bit and found this post:
https://ubuntuforums.org/archive/index.php/t-1721081.html

> Anyway fixed the issue. There where two problems: the passive port range and the order of -c and -p.
>
> The port range based on my first case was: (40115 + 1 - 40110) / 2=3
>
> And ubuntu doesn't ensure -c comes before -p, so if you use the default config and run script in /etc/init.d/pure-ftpd then it will not work (even if you get the port range correct).

i did exactly the same mistakes and following this i fixed my issue, do you think you could make this more clear in the README?

**Comment by stilliard** [comment]
Hi @deathcoder ,
Thanks, would you be interested to submit a pull request with your proposed changes to the README? :)
