### ISSUE TITLE
No renaming of files/directories possible?

### ISSUE THREAD

**Issue by rogierlommers** [stilliard/docker-pure-ftpd#49]
For some reason, I'm unable to rename directories/files inside a FTP user's home folder. First some information about what I do:

- Start container: `docker run -d --name ftpd_server -p 21:21 -p 30000-30009:30000-30009 -e "PUBLICHOST=localhost" -e "ADDED_FLAGS=-d -d" stilliard/pure-ftpd:hardened`
- Enter running container: `docker exec -it ftpd_server /bin/bash`
- Add user: `pure-pw useradd blabla -f /etc/pure-ftpd/passwd/pureftpd.passwd -m -u ftpuser -d /home/ftpusers/blabla` with password

Now I can login using user `blabla` and see the contents of directory (/home/ftpusers/blabla). Here I can upload files to, download from, but for some reason I'm unable to rename files/directories. I get this:

<img width="391" alt="screen shot 2017-10-04 at 17 05 45" src="https://user-images.githubusercontent.com/3907131/31183244-481f95c2-a926-11e7-80da-0bb9bcfab5fd.png">

Any idea what I'm doing wrong?

**Comment by mattli001** [comment]
The run option is "NoRename" in the  "stilliard/pure-ftpd:hardened".
ref: https://github.com/stilliard/docker-pure-ftpd/issues/10#issuecomment-153999875
code: https://github.com/stilliard/docker-pure-ftpd/blob/hardened/Dockerfile#L64 
`-G      --norename`

**Comment by rogierlommers** [comment]
Thanks; would be nice if we can make this an option? Maybe through environment vars?

**Comment by stilliard** [comment]
Hey :), feel free to suggest any ENV vars like this with a pull request 👍

**Comment by JieChungChang** [comment]
Sorry for asking after closed this issue.
But I still don't know how to allow user rename exist file. 
I add a NoRename file in "/etc/pure-ftpd/conf" and the content is no but it isn't working for me.

**Comment by stilliard** [comment]
Hi @JieChungChang 
The /etc/pure-ftpd/conf folder is not used in this project however all these conf files relate to pureftpd flags. 
The :hardened comes with a bunch of security defaults like this passed as flags when starting the container, but if you switch to :latest it'll let you rename again. 
You can also specify the flags to pass to pureftpd, see more info on this in the README.md file.
Hope this helps.

**Comment by JieChungChang** [comment]
It works! 
Thanks! Really helpful for me!
