### ISSUE TITLE
Question-Regarding authantication

### ISSUE THREAD

**Issue by pratapnanda** [stilliard/docker-pure-ftpd#50]
Hello.
I run below command to create a container 
 	docker run -d --name ftp_server -p 21 -e "PUBLICHOST=localhost" stilliard/pure-ftpd:hardened
 	pure-pw useradd RALLIPROD -f /etc/pure-ftpd/passwd/pureftpd.passwd -m -u ftpuser -d /home/ftpusers/RALLIPROD

Now I am trying to connect from another container but my issue is how to pass username and credential in on FTP  command  

[root@aefd3ba6593e /]# ftp -p ftp_server
Connected to ftp_server (10.0.108.6).
220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
220-You are user number 2 of 5 allowed.
220-Local time is now 14:36. Server port: 21.
220-This is a private system - No anonymous login
220 You will be disconnected after 15 minutes of inactivity.
Name (ftp_server:root): RALLIPROD
331 User RALLIPROD OK. Password required
Password:
230 OK. Current directory is /
Remote system type is UNIX.
Using binary mode to transfer files.
ftp> exit
221-Goodbye. You uploaded 0 and downloaded 0 kbytes.
221 Logout.

[root@aefd3ba6593e /]# ftp ftp_server RALLIPROD/abc123
ftp: ftp_server RALLIPROD/abc123: Servname not supported for ai_socktype

**Comment by stilliard** [comment]
Hey @pratapnanda , 
Apologies for the very delayed reply, i've not been working with this container much lately. 
The "Servname not supported for ai_socktype" isn't one i've run into before, did you find a solution for this in end?
