### ISSUE TITLE
Can't connect to FTP inside docker container

### ISSUE THREAD

**Issue by yudao** [stilliard/docker-pure-ftpd#54]
Hi,

I have a droplet with an app dockerized and docker-pure-ftpd together.

I've run the container:
```bash
docker run -d --name FTP -e "PUBLICHOST=ftp.myftp.com" -p 21:21 -p 30000-30009:30000-30009 -v /var/lib/dokku/data/storage/ftp:/home/ftpusers -v /var/lib/dokku/data/storage/pureftp/:/etc/pure-ftpd stilliard/pure-ftpd
```

On the host or with any client I can connect to FTP. On my app container I've got always "Connection time out".

Is there a way to fix that?

Thanks a lot!

Yu.

**Comment by stilliard** [comment]
Hi @yudao ,
Apologies for they delayed reply, did you find the cause of this in the end?
If not, i'd check your firewall on the app to make sure the ftp port is open.

**Comment by yudao** [comment]
Hi @stilliard,
No problem, same here :)
Yes it was a firewall issue.
Sorry for the disturbing.
Thank you!
