### ISSUE TITLE
Is it possible to mount the file of users ? 

### ISSUE THREAD

**Issue by kevincaradant** [stilliard/docker-pure-ftpd#55]
Hi

I will install a soft to update automatically the docker image when a new will be created.

As you can understand, the problem is about the users authorized which are inside the image ...

Do you think if it's possible to create the users via the read of a file ( using -v option of docker)  ? 

Thank you

**Comment by stilliard** [comment]
Hi @kevincaradant ,
Apologies, I've not been working with this repo much lately. 
Did you find an answer to this in the end? 
If not, you could setup a cron to pull the latest version of this image down and then stop the current one and instantly start the next.

**Comment by kevincaradant** [comment]
Hi 

Apologies too, I forgot to answer you when I saw your answer ...

I decided to use an other image and mostly an other protocol, so my request can be closed as you already done :)

Regards

**Comment by kevincaradant** [comment]
Hi 

Apologies too, I forgot to answer you when I saw your answer ...

I decided to use an other image and mostly an other protocol, so my request can be closed as you already done :)

Regards
