### ISSUE TITLE
only ftps allow

### ISSUE THREAD

**Issue by iterprise** [stilliard/docker-pure-ftpd#57]
Can i allow only ftps? Without pure ftp

**Comment by stilliard** [comment]
Hi @iterprise,
Yes you can, I believe to do this you'll need to set tls to 2 which should refuse insecure connections.
With this container you can do this by passing the following env flag to docker run
-e "ADDED_FLAGS=--tls=2"
More details on using this here: https://github.com/stilliard/docker-pure-ftpd#starting-it

You'll also need a valid certificate, more info on these here: https://github.com/stilliard/docker-pure-ftpd#tls

Hope this helps.

**Comment by TheLeftMoose** [comment]
@stilliard i just found out that running the :hardend tag, it sets the tls to 1. 

Furthermore can't start if you have added the -e "ADDED_FLAGS=--tls=2"

**Comment by stilliard** [comment]
Hi @TheLeftMoose ,

Yes the container will set this flag to 1 by default if you don't set ADDED_FLAGS to the above or if you volume in /etc/ssl/private/pure-ftpd.pem  ref: https://github.com/stilliard/docker-pure-ftpd/blob/master/run.sh#L21

The ADDED_FLAGS should work, could you paste some example commands to show this not working for you?

**Comment by TheLeftMoose** [comment]
@stilliard I think my problem was linux and quotes. docker-compose file that works: https://gist.github.com/TheLeftMoose/c3fb49930f2e5ad0fe1a552aa065e06b

**Comment by stilliard** [comment]
Ah that's cool, glad you've got it working. 
Would you be interested in contributing a ocker-compose.yml file like this to the project & adding a little about it in the README? I'm sure it'd be useful to many other users thank you.
