### ISSUE TITLE
pure-ftpd stat /var/lib/docker/tmp/docker-builder 191299239/run.sh: no such file or directory

### ISSUE THREAD

**Issue by cornelius80** [stilliard/docker-pure-ftpd#63]
Hi Stilliard,

I encountered the following while building the docker container with the dockerfile provided.

pure-ftpd stat /var/lib/docker/tmp/docker-builder 191299239/run.sh: no such file or directory

Please advise.
Thank you.

Kind Regards,
Cornelius

**Comment by cornelius80** [comment]
Hi Andrew,

Yes.
I have simply copied the entire dockerfile and ran a build.

Regards,
Cornelius

**Comment by stilliard** [comment]
No problem you'll need the run.sh file too (https://github.com/stilliard/docker-pure-ftpd/blob/master/run.sh)
This file is run when it starts up.
Hope this helps.

**Comment by cornelius80** [comment]
Ah I see..ok.

Thank you for your advice,Andrew

Regards,
Cornelius

**Comment by stilliard** [comment]
No problem, happy to help out
