### ISSUE TITLE
Unable to close the database: Device or resource busy

### ISSUE THREAD

**Issue by yudao** [stilliard/docker-pure-ftpd#65]
Hi,

I'm facing off a non comprehensive problem.

I have already 4 virtual users. Now I want to create the 5th :

```bash
pure-pw useradd mynewuser -u ftpuser -g ftpgroup -f /etc/pure-ftpd/passwd/pureftpd.passwd -d /home/ftpusers/mynewuser -m
Password:
Enter it again:
Unable to close the database: Device or resource busy
```

Same If I remove -m flag and run pure-pw mkdb

I've stopped and restarted my docker with no luck.

Do you have an idea how to solve this problem?

Thanks a lot.

Yu.

**Comment by stilliard** [comment]
Hi @yudao ,

I've not seen that before sorry, and a quick google didn't return much. 

Might be worth asking on stackoverflow if you haven't already, i'm sure someone on there can help with this.

**Comment by yudao** [comment]
Thanx @stilliard for your quick response.
I leave this issue open and get back with the resolution if I found it.

**Comment by yudao** [comment]
I found the problem (I think....).

The pureftpd.pdb file was mounted as a volume. I've removed the mount and keep only the pureftpd.passwd file mount.

Now all is fine.
