### ISSUE TITLE
Large file upload unexpectedly stops

### ISSUE THREAD

**Issue by whitechevyss** [stilliard/docker-pure-ftpd#67]
I am able to upload small files fine. When I try to upload a large iso (~9GB) the file gets about 50% though (~5 minutes) and goes to fully complete. When I look at the data directory on the server or refresh the client, the file is not there. I've added the to logging options but nothing is getting logged.

**Comment by stilliard** [comment]
Hey @whitechevyss , 
Sorry for not getting back to you sooner.
I admittedly haven't tested with a very large file like this, but I'm downloading windows 10 now (4.4gb) to test with. 
I'll let you know how it goes.

**Comment by stilliard** [comment]
Closing this for now but please let me know if there's still any issue.
