### ISSUE TITLE
maybe latest container image has some exception

### ISSUE THREAD

**Issue by guodidi** [stilliard/docker-pure-ftpd#69]
**first, thanks for your pure-ftp docker image.** 

I use the image is upload before 10 day , i want to use the feature thar when pure-ftp container started and auto create a ftp user for me . but when i use your supply command , but find the ftp user cannot auto create ftp user. so i use 
```
docker save -o pure-ftp.tar stilliard/pure-ftpd
```
 to download the image . when i  decompression the tar file , at root path i find a file name is repositories file 
```
{"stilliard/pure-ftpd":{"hardened":"0c46ff2a52fffb1bccda128c1521f64f9531e30db1b8fd11d922a93b24f7114a","latest":"1979a335a13f3bd97cc8bf3bf764a2e7365de0e6e4930bb1009862f9533714e1"}}
```
so i see the directory `1979a335a13f3bd97cc8bf3bf764a2e7365de0e6e4930bb1009862f9533714e1`
at this directory and i found a layer.tar . so i decompression the layer.tar, and found the run.sh 

the run.sh content is 
```
#!/bin/bash

# build up flags passed to this file on run + env flag for additional flags
# e.g. -e "ADDED_FLAGS=--tls=2"
PURE_FTPD_FLAGS="$@ $ADDED_FLAGS "

# start rsyslog
if [[ "$PURE_FTPD_FLAGS" == *" -d "* ]] || [[ "$PURE_FTPD_FLAGS" == *"--verboselog"* ]]
then
	echo "Log enabled, see /var/log/messages"
	rsyslogd
fi

# Load in any existing db from volume store
if [ -e /etc/pure-ftpd/passwd/pureftpd.passwd ]
then
    pure-pw mkdb /etc/pure-ftpd/pureftpd.pdb -f /etc/pure-ftpd/passwd/pureftpd.passwd
fi

# detect if using TLS (from volumed in file) but no flag set, set one
if [ -e /etc/ssl/private/pure-ftpd.pem ] && [[ "$PURE_FTPD_FLAGS" != *"--tls"* ]]
then
    echo "TLS Enabled"
    PURE_FTPD_FLAGS="$PURE_FTPD_FLAGS --tls=1 "
fi

# let users know what flags we've ended with (useful for debug)
echo "Starting Pure-FTPd:"
echo "  pure-ftpd $PURE_FTPD_FLAGS"

# start pureftpd with requested flags
exec /usr/sbin/pure-ftpd $PURE_FTPD_FLAGS
```
the content not latest run.sh file , so i want to know , whether you forget to build the run.sh file into the latest image .

**only latest has somethind error , hardened is ok.** 

thanks you.

**Comment by stilliard** [comment]
Hey @guodidi ,
that is weird, did you pull down the latest version first with `docker pull stilliard/pure-ftpd` ?

I've merged in your latest change and pushed a new docker image up so if you could pull this down now and then try again the run.sh should be updated. 

Hope this helps :)

**Comment by guodidi** [comment]
hey @stilliard , i try this latest version container image. it can works.  thanks for your help .  i will close this issue .
