### ISSUE TITLE
Using exec form of CMD

### ISSUE THREAD

**Issue by WouldYouKindly** [stilliard/docker-pure-ftpd#72]
Hi. I noticed that you use shell form of CMD in the Dockerfile. This prevents pure-ftpd from receiving signals. This leads to slow `docker stop` (docker waits ten seconds and sends SIGKILL).

I tried the naive approach and replaced CMD string with array, but exec form does not allow environment variables expansion. The solution may be to move specifying the host in `run.sh`:

```
------------
exec /usr/sbin/pure-ftpd $PURE_FTPD_FLAGS
+++++++++++
exec /usr/sbin/pure-ftpd $PURE_FTPD_FLAGS $PUBLICHOST
```

What are your thoughts on that? I understand this is kind of a small issue, but when I set up FTP server, I had to restart it a lot to figure out how to do certain things. It would be nice if restarts were fast.

**Comment by stilliard** [comment]
Hey @WouldYouKindly ,
Sorry I hadn't got back to you earlier about this issue or your pull request. 

That is interesting, I'd not noticed the delay before.

I'm not sure if moving the $PUBLICHOST variable will change anything though as $PURE_FTPD_FLAGS should already contain this. 

You could fork or extend this image to try out some ideas, worth a test I think.
If you find a solution let me know or open a pull request & I'd be happy to try it out & merge it in.

**Comment by WouldYouKindly** [comment]
@stilliard my pull-request sucked anyway, so no big deal (: 

Moving `$PUBLICHOST` from `Dockerfile` to `run.sh` allows to use exec form of CMD. I'll send a PR shortly.

**Comment by stilliard** [comment]
Hey @WouldYouKindly ,

I've just realised why i'd not noticed the delay of 10 seconds or so like you mentioned. I use `docker kill` instead of `docker stop` during development which sends SIGKILL right away.

Would using this resolve the issue for you?

**Comment by stilliard** [comment]
Not sure about the odd comment lol, but simplicity wins every time :).

Thanks for your contribution anyway & i hope `docker kill` or your fork works well for you.

**Comment by WouldYouKindly** [comment]
@stilliard sorry if my comment sounded offensive! It was not intended as such.

**Comment by splattael** [comment]
@WouldYouKindly I've stumbled on the same PID 1 issues as you did. Nowadays, one can use `docker run --init` to start a container which you can normally stop via `docker stop`.

I hope this helps :)

**Comment by WouldYouKindly** [comment]
@splattael thanks! We made our own Dockerfile, since we needed a couple of other customizations.
