### ISSUE TITLE
[Question] Setting the number of users.

### ISSUE THREAD

**Issue by bheku** [stilliard/docker-pure-ftpd#77]
In the documentation, it is recommended to extend the image and make changes as needed.

However, I just need to change the maximum number of users, -c, to a larger number. Do I still need to create my own image just for that change only?

Or is there any other way to override the default value of 5?

**Comment by stilliard** [comment]
Hi @bheku ,

Sure you can run set the run command when using docker run to override this instead, see here for more details: https://docs.docker.com/engine/reference/run/

**Comment by bheku** [comment]
Not sure I follow.  Do you have an example?

And thanks for the the work thus far.

**Comment by stilliard** [comment]
Sure thing, I believe the following syntax would work, this gets around any need for adding variables for every pure-ftpd setting :)

```
docker run --rm -d --name ftpd_server -p 21:21 -p 30000-30009:30000-30009 stilliard/pure-ftpd:hardened bash /run.sh -c 30 -C 10 -l puredb:/etc/pure-ftpd/pureftpd.pdb -E -j -R -P localhost -p 30000:30059
```

**Comment by bheku** [comment]
Thank you:

Status:	Connection established, waiting for welcome message...
Response:	220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
Response:	220-You are user number 4 of 30 allowed.
Response:	220-Local time is now 09:51. Server port: 21.
Response:	220-This is a private system - No anonymous login
Response:	220-IPv6 connections are also welcome on this server.
Response:	220 You will be disconnected after 15 minutes of inactivity.

**Comment by stilliard** [comment]
You're welcome, I'll add this to the docs

**Comment by bheku** [comment]
Nah... add an environment variable rather, FTP_MAX_CLIENTS... it makes for a rather lengthier having to invoke the run.sh file and it's arguments.

Don't you think?

**Comment by stilliard** [comment]
I'd always air on the side of simplicity. There's many flags I could add but they'd just map to the pure-ftpd ones so seems pointless unless there's a real gain. 
Full list of flags available: https://linux.die.net/man/8/pure-ftpd (adding these to the readme now)
