### ISSUE TITLE
Max users number

### ISSUE THREAD

**Issue by DmitryVorobets** [stilliard/docker-pure-ftpd#78]
There's no way to change max users:
docker-compose.yml:
  ftp:
    image: stilliard/pure-ftpd #dockerhub.tom.takeoff.com/ftp
    ports:
      - "10.99.0.27:21:21"
      - "30000-30099:30000-30099"
    volumes:
      - "./ftp/data:/home/xxxxxx/host"
      - "./ftp/passwd:/etc/pure-ftpd/passwd"
      - "./ftp/log:/var/log"
    environment:
      PUBLICHOST: "0.0.0.0"
      FTP_USER_NAME: "xxxxxx"
      FTP_USER_PASS: "xxxxxx"
      FTP_USER_HOME: "/home/xxxxxx/host"
      ADDED_FLAGS: "-d -d -c 50 -p 30000:30099"
    restart: always
`env` from container
    ADDED_FLAGS=-d -d -c 50 -p 30000:30099
docker inspect:
   command: "/run.sh -c 5 -C 5 -l puredb:/etc/pure-ftpd/pureftpd.pdb -E -j -R -P $PUBLICHOST"
Response:
  220-You are user number 5 of 5 allowed.

Also i rebuilt a container with this Dockerfile:
    FROM stilliard/pure-ftpd
    CMD /run.sh -c 30 -C 10 -l puredb:/etc/pure-ftpd/pureftpd.pdb -E -j -R -P $PUBLICHOST -p 30000:30059
and there's no effect.
Also see at this:
   root@c85604da87ff:/# ls /etc/pure-ftpd/conf/
   AltLog	   MinUID	PAMAuthentication  TLSCipherSuite
   FSCharset  NoAnonymous	PureDB UnixAuthentication
there're no MaxConnection's files.
So this container is broken from scratch. Don't use it, it's a pain for your brain

**Comment by stilliard** [comment]
Hi @DmitryVorobets ,
Sorry you felt the need to say it's broken ;). 
It's actually not, we just don't use the debian conf system for those files. 
Please use flags instead, thank you,

**Comment by DmitryVorobets** [comment]
Connected to 10.99.0.27.
220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
220-You are user number 3 of 5 allowed.
220-Local time is now 13:03. Server port: 21.
220-This is a private system - No anonymous login
220-IPv6 connections are also welcome on this server.
220 You will be disconnected after 15 minutes of inactivity.
Name (10.99.0.27:wara): 
After this "fix":
https://github.com/stilliard/docker-pure-ftpd/issues/77

**Comment by DmitryVorobets** [comment]
Andrew, sorry about my words, but i tried to configure it by many ways, it isn't work. There's always 5 users max

**Comment by stilliard** [comment]
by this "fix" do you mean that you're now passing the flag to change it?

**Comment by stilliard** [comment]
Have you tried increasing the passive port range?
That might help as i believe pure-ftpd ties users to this e.g. -e "FTP_PASSIVE_PORTS=30000:30100"

**Comment by DmitryVorobets** [comment]
Andrew, thx 2 u a lot! This works.
