### ISSUE TITLE
Unable to increase Max clients 

### ISSUE THREAD

**Issue by zhaozhouyang** [stilliard/docker-pure-ftpd#86]
Hi, I run this ftp with following command:
docker run -d --name ftpd_server -v /home/ftp:/var/lib/ftp -p 21:21 -p 30000-30099:30000-30099 -e "PUBLICHOST=******" -e FTP_MAX_CLIENTS=50 -e FTP_MAX_CONNECTIONS=50 -e FTP_USER_NAME=ftpuser -e FTP_PASSIVE_PORTS=30000:30099 -e FTP_USER_PASS=***** -e FTP_USER_HOME=/var/lib/ftp --privileged=true stilliard/pure-ftpd:hardened

but still got this error when there are more than 5 clients and connections:
![image](https://user-images.githubusercontent.com/20453416/46901821-32397f00-ceed-11e8-9455-cb969781925c.png)

Do you have any idea how to config it?

Thank you:)

**Comment by stilliard** [comment]
Hi @zhaozhouyang ,

Have you tried pulling down the latest image:

```
docker pull stilliard/pure-ftpd:hardened
```

If that doesn't help, could you please provide me the docker logs output for your container?

Thanks.

**Comment by stilliard** [comment]
Closing for now but please reopen if the issue persists for you

**Comment by neptunao** [comment]
It perists for me in hardened version.

**Comment by neptunao** [comment]
`docker logs`:
```Log enabled, see /var/log/messages
Creating user...
Password:
Enter it again:
Setting default port range to: 30000:30009
Setting default max clients to: 50
Setting default max connections per ip to: 50
Starting Pure-FTPd:
  pure-ftpd -l puredb:/etc/pure-ftpd/pureftpd.pdb -E -j -R -P localhost -s -A -j -Z -H -4 -E -R -G -X -x -d -d  -p 30000:30009 -c 50 -C 50
```
 `docker exec -it ftpd tail -f /var/log/messages`: 
```Dec  5 12:40:07 neptunao-lt pure-ftpd: (?@127.0.0.1) [INFO] New connection from 127.0.0.1
Dec  5 12:40:07 neptunao-lt pure-ftpd: (?@127.0.0.1) [INFO] bob is now logged in
Dec  5 12:40:07 neptunao-lt pure-ftpd: (?@127.0.0.1) [INFO] bob is now logged in
Dec  5 12:40:07 neptunao-lt pure-ftpd: (?@127.0.0.1) [INFO] bob is now logged in
Dec  5 12:40:07 neptunao-lt pure-ftpd: (?@127.0.0.1) [INFO] bob is now logged in
Dec  5 12:40:07 neptunao-lt pure-ftpd: (bob@127.0.0.1) [INFO] Logout.
Dec  5 12:40:07 neptunao-lt pure-ftpd: (bob@127.0.0.1) [INFO] Logout.
Dec  5 12:40:07 neptunao-lt pure-ftpd: (bob@127.0.0.1) [INFO] Logout.
Dec  5 12:40:07 neptunao-lt pure-ftpd: (bob@127.0.0.1) [INFO] Logout.
Dec  5 12:40:07 neptunao-lt pure-ftpd: (bob@127.0.0.1) [INFO] Logout.
```

**Comment by neptunao** [comment]
Nevermind, setting `FTP_PASSIVE_PORTS=30000:30099` resolved the issue.

**Comment by zh554275855** [comment]
@neptunao 
Setting default port range to: 30000:30099
zookeeper_1              | 2019-04-03 08:48:32,860 [myid:] - WARN  [main:QuorumPeerMain@116] - Either no config or no quorum defined in config, running  in standalone mode
pure_vsftpd              | Setting default max clients to: 5
pure_vsftpd              | Setting default max connections per ip to: 5

Could you pls help me, how to set max clients?

**Comment by stilliard** [comment]
Hi @zh554275855 , 
Have you tried setting the FTP_PASSIVE_PORTS env var to 30000:30099?
Hope this helps

**Comment by zh554275855** [comment]
Hi @stilliard, 
I have set this in docker-compose.yml , then FTP started with 'Setting default port range to: 30000:30099', but the max clients of FTP also was 5, I want to increace the number of max clients via docker-compose.yml file, so what should I do? Thanks for you quick response.

**Comment by stilliard** [comment]
Ah ok, no problem. 
Have you also tried adding `FTP_MAX_CLIENTS=50` and `FTP_MAX_CONNECTIONS=50` ?

**Comment by zh554275855** [comment]
@stilliard It works now, thank you very much
