### ISSUE TITLE
MLSD Error:	Connection timed out after 20 seconds of inactivity

### ISSUE THREAD

**Issue by AlexCloudDev** [stilliard/docker-pure-ftpd#87]
Hello,
i have a problem with MLSD and connection timeouts.
My pure-ftpd server is started with this command:
`pure-ftpd -l extauth:/var/run/pure-ftpd/authd.sock -d -O clf:/var/log/pureftpd.log -j -A -E -p 8081:8089 -P 1.2.3.4 --tls=1`

The container uses a user-defined bridge network. All ports are bind to a IP address of the host:
192.168.2.2:21->21/tcp, 192.168.2.2:8181-8189->8181-8189/tcp

Port forwarding for all ports (21, 8181-8989) is set at my router and in the docker-compose.yml file:
..
    container_name: ftp_server
    restart: always
    ports:
      - 21-21:21-21
      - 8181-8189:8181-8189
    volumes:
      - ./user:/var/userdata
      - ./../proxy/etc/nginx/certs:/opt/certs:ro
..

rsyslog:
pure-ftpd: (?@***.com) [INFO] New connection from ***.com
pure-ftpd: (?@***.com) [DEBUG] Command [auth] [TLS]
pure-ftpd: (?@***.com) [INFO] TLS: Enabled TLSv1.2 with ECDHE-RSA-CHACHA20-POLY1305, 256 secret bits cipher
pure-ftpd: (?@***.com) [DEBUG] Command [user] [alex]
pure-ftpd: (?@***.com) [DEBUG] Command [pass] [<*>]
/pureftpd_pwcheck.py: asked to authorize alex
/pureftpd_pwcheck.py: authorization successful
pure-ftpd: (?@***.com) [INFO] alex is now logged in
pure-ftpd: (alex@***.com) [DEBUG] Command [pbsz] [0]
pure-ftpd: (alex@***.com) [DEBUG] Command [prot] [P]
pure-ftpd: (alex@***.com) [DEBUG] Command [pwd] []
pure-ftpd: (alex@***.com) [DEBUG] Command [type] [I]
pure-ftpd: (alex@***.com) [DEBUG] Command [pasv] []
pure-ftpd: (alex@***.com) [DEBUG] Command [mlsd] []

FileZilla log:
Status:	Resolving address of ***.com
Status:	Connecting to 1.2.3.4:21...
Status:	Connection established, waiting for welcome message...
Status:	Initializing TLS...
Status:	Verifying certificate...
Status:	TLS connection established.
Status:	Server does not support non-ASCII characters.
Status:	Logged in
Status:	Retrieving directory listing...
Command:	PWD
Response:	257 "/" is your current location
Command:	TYPE I
Response:	200 TYPE is now 8-bit binary
Command:	PASV
Response:	227 Entering Passive Mode (1,2,3,4,31,149)
Command:	MLSD
Error:	Connection timed out after 20 seconds of inactivity
Error:	Failed to retrieve directory listing

Any clues ?

Thank you in advance
regards

**Comment by AlexCloudDev** [comment]
Hi,
thx for your reply.
I'm still experiencing the error.

The IP following the -P flag is my external IP i got from my provider.
I tried it with "localhost" or the container ip, but this didn't work either.
It gave me a error message at Filezilla.

But i can check it again.


What else IP/hostname can i try?

regards

**Comment by stilliard** [comment]
Hi @AlexCloudDev 
Apologies, i thought I'd replied to this a month ago. 

Did you ever get this working in the end?

**Comment by Inv0k-er** [comment]
Sorry and how to fix it ?
