### ISSUE TITLE
Uploading file with .NET Core v2.1

### ISSUE THREAD

**Issue by TobiasMorell** [stilliard/docker-pure-ftpd#94]
Hello.

I'm trying to upload a file to the FTP server with ASP.Net Core v2.1. I want to accept a request from the browser, which contains username, password, a file and the FTP server to upload the file to. The ASP.Net server must thus simply relay the request from the browser. When I do so I get an exception, stating:

> System.Net.WebException: The remote server returned an error: 227 Entering Passive Mode (172,17,0,2,24,3)
. ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: Connection refused 127.0.0.1:6147

From what I could understand this exception occurs when the server does not accept socket connections on the given port (in this case 6147). I have launched the docker with a docker-compose:
> pureftpd:
  image: vimagick/pure-ftpd
  ports:
    - "21:21"
    - "27559:27559"
    - "6147:6147"
  volumes:
    - ./data/ftpuser:/home/ftpuser
    - ./data/pure-ftpd:/etc/pure-ftpd
  privileged: true
  restart: always`

I attempt to upload it to **ftp://localhost:21/kev/file.txt**. Is this something wrong with the docker-compose?

**Comment by stilliard** [comment]
Hi @TobiasMorell ,

Looks like you're using `vimagick/pure-ftpd` instead of this repo which is `stilliard/pure-ftpd`. 

Try changing to that & then checkout our standard docker-compose.yml file for help: https://github.com/stilliard/docker-pure-ftpd/blob/master/docker-compose.yml

**Comment by TobiasMorell** [comment]
Thank you for your reply.

I followed your advice and everything is now working perfectly!
