### ISSUE TITLE
32bit support - Error after creating the container with docker image.

### ISSUE THREAD

**Issue by BiroStorm** [stilliard/docker-pure-ftpd#95]
Hey,
I'm following the Basic example on Wiki, but after creating the container with run command, it exited with 1 error:

> standard_init_linux.go:178: exec user process caused "exec format error"

I don't know if it is depended on my Operative System Ubuntu Server 16.04.2...

Does anyone know why I have this error?

**Comment by BiroStorm** [comment]
Yeah, it's Ubuntu 16.04 because now I'm using 18.10 and all works fine.

**Comment by BiroStorm** [comment]
I used 2 commands:
`docker pull stilliard/pure-ftpd:hardened` 
and after
`docker run --rm -d --name ftpd_server -p 21:21 -p 30000-30009:30000-30009 stilliard/pure-ftpd:hardened bash /run.sh -c 30 -C 10 -l puredb:/etc/pure-ftpd/pureftpd.pdb -E -j -R -P localhost -p 30000:30059`
after this I checked with `docker ps -a` that my container status was exited with 1 error so I did `docker logs idcontainer` and printed out the error.
I have an Intell Processor but maybe you are right, the version 16.04 was 32bit and the new one 18.10 is 64bit... so maybe it's cause of that problem.

Thank :D

**Comment by stilliard** [comment]
Glad the 64bit versions working for you. 

I'll keep the ticket open to see if anyone can get it working on 32bit,
but for now my advice to anyone else reading this is to try 64bit.

**Comment by robsdedude** [comment]
I'm also seeing this error trying to run this image on a Raspberry Pi (ARM). So maybe you should add to the readme that this image is only tested for x86_64…
