### ISSUE TITLE
Indentation Error

### ISSUE THREAD

**Issue by BiroStorm** [stilliard/docker-pure-ftpd#97]
Hey, I just found an indentation error on [Docker stack with Wordpress & FTP](https://github.com/stilliard/docker-pure-ftpd/wiki/Docker-stack-with-Wordpress-&-FTP).

If you copy and paste, and run compose up will give you 

> while passing a block mapping in [...] expected <block end>, but found '<block mapping start>' in [...]

Just need to add a blank space in Line 8.
Thanks.

**Comment by stilliard** [comment]
Thanks @BiroStorm , I've updated the wiki :+1: 

Merry Christmas! :santa: :gift:
